<?php

namespace App\Services;

use App\AccountTransaction;
use App\Events\PurchaseCreatedOrModified;
use App\PurchaseLine;
use App\Transaction;
use App\TransactionPayment;
use App\Utils\ProductUtil;
use App\Utils\TransactionUtil;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Modules\StorageManager\Entities\StorageApprovalRequest;
use Modules\StorageManager\Entities\StorageDocument;
use Modules\StorageManager\Entities\StorageDocumentLine;
use Modules\StorageManager\Entities\StorageDocumentLink;
use Modules\StorageManager\Entities\StorageInventoryMovement;
use Modules\StorageManager\Entities\StorageSyncLog;
use Modules\StorageManager\Entities\StorageTask;
use Modules\StorageManager\Entities\StorageTaskEvent;
use Modules\StorageManager\Services\PutawayService;
use Modules\StorageManager\Services\ReceivingService;
use Modules\StorageManager\Utils\StorageVasReceiptSyncUtil;
use Modules\VasAccounting\Services\VasPostingService;
use RuntimeException;

class PurchaseOrderDeletionService
{
    public function __construct(
        protected ProductUtil $productUtil,
        protected TransactionUtil $transactionUtil,
        protected ReceivingService $receivingService,
        protected PutawayService $putawayService,
        protected StorageVasReceiptSyncUtil $storageVasReceiptSyncUtil,
        protected VasPostingService $vasPostingService
    ) {
    }

    public function delete(int $businessId, int $purchaseOrderId, int $userId): array
    {
        return DB::transaction(function () use ($businessId, $purchaseOrderId, $userId) {
            $purchaseOrder = Transaction::query()
                ->where('business_id', $businessId)
                ->where('type', 'purchase_order')
                ->with('purchase_lines')
                ->findOrFail($purchaseOrderId);

            $generatedPurchases = $this->generatedPurchasesForOrder($businessId, $purchaseOrderId);
            $blockingPurchases = $this->blockingPurchasesForOrder($businessId, $purchaseOrderId, $generatedPurchases->pluck('id'));
            if ($blockingPurchases->isNotEmpty()) {
                throw new RuntimeException(
                    'Purchase order cannot be deleted because linked purchase(s) were not generated by StorageManager: '
                    . $blockingPurchases
                        ->map(fn (Transaction $purchase) => (string) ($purchase->ref_no ?: $purchase->invoice_no ?: ('#' . $purchase->id)))
                        ->implode(', ')
                );
            }

            $summary = [
                'putaways_reopened' => 0,
                'receipts_reopened' => 0,
                'storage_documents_deleted' => 0,
                'purchase_returns_deleted' => 0,
                'payments_deleted' => 0,
                'generated_purchases_deleted' => 0,
                'vas_links_removed' => 0,
            ];

            $receiptDocuments = $this->receiptDocumentsForOrder($businessId, $purchaseOrderId, $generatedPurchases);
            $putawayDocuments = $this->putawayDocumentsForReceipts($businessId, $receiptDocuments->pluck('id'));

            foreach ($putawayDocuments as $putawayDocument) {
                if ($this->requiresVasUnlink($putawayDocument)) {
                    $this->storageVasReceiptSyncUtil->unlinkDocumentVasSync($businessId, $putawayDocument, $userId);
                    ++$summary['vas_links_removed'];
                }

                if (in_array((string) $putawayDocument->status, ['completed', 'closed'], true)) {
                    $this->putawayService->reopenPutaway($businessId, $putawayDocument, $userId);
                    ++$summary['putaways_reopened'];
                }
            }

            foreach ($receiptDocuments as $receiptDocument) {
                if ($this->requiresVasUnlink($receiptDocument)) {
                    $this->storageVasReceiptSyncUtil->unlinkDocumentVasSync($businessId, $receiptDocument, $userId);
                    ++$summary['vas_links_removed'];
                }

                if (! in_array((string) $receiptDocument->status, ['completed', 'closed'], true)) {
                    continue;
                }

                if ($this->isGeneratedPurchaseOrderReceipt($receiptDocument)) {
                    $this->receivingService->reopenGeneratedPurchaseOrderReceiptForDeletion($businessId, $receiptDocument, $userId);
                } else {
                    $this->receivingService->reopenReceipt($businessId, $receiptDocument, $userId);
                }
                ++$summary['receipts_reopened'];
            }

            foreach ($this->putawayDocumentsForReceipts($businessId, $receiptDocuments->pluck('id')) as $putawayDocument) {
                $this->deleteStorageDocumentCascade($businessId, $putawayDocument);
                ++$summary['storage_documents_deleted'];
            }

            foreach ($this->receiptDocumentsForOrder($businessId, $purchaseOrderId, $generatedPurchases) as $receiptDocument) {
                $this->deleteStorageDocumentCascade($businessId, $receiptDocument);
                ++$summary['storage_documents_deleted'];
            }

            foreach ($generatedPurchases as $generatedPurchase) {
                foreach ($this->purchaseReturnsForPurchase($businessId, (int) $generatedPurchase->id) as $purchaseReturn) {
                    $this->deletePurchaseReturn($purchaseReturn, $businessId, $userId, $summary);
                }

                foreach ($generatedPurchase->payment_lines as $payment) {
                    TransactionPayment::deletePayment($payment);
                    ++$summary['payments_deleted'];
                }

                $this->deleteGeneratedPurchase($generatedPurchase, $businessId);
                ++$summary['generated_purchases_deleted'];
            }

            $logProperties = [
                'id' => $purchaseOrder->id,
                'ref_no' => $purchaseOrder->ref_no,
            ];
            $this->transactionUtil->activityLog($purchaseOrder, 'po_deleted', null, $logProperties);

            PurchaseLine::query()
                ->where('transaction_id', $purchaseOrder->id)
                ->delete();
            $purchaseOrder->delete();

            return [
                'success' => true,
                'msg' => $this->summaryMessage($summary),
                'summary' => $summary,
            ];
        });
    }

    protected function generatedPurchasesForOrder(int $businessId, int $purchaseOrderId): Collection
    {
        return Transaction::query()
            ->where('business_id', $businessId)
            ->where('type', 'purchase')
            ->where('source', ReceivingService::GENERATED_PURCHASE_SOURCE)
            ->with(['purchase_lines', 'payment_lines'])
            ->orderByDesc('id')
            ->get()
            ->filter(function (Transaction $transaction) use ($purchaseOrderId) {
                return collect((array) $transaction->purchase_order_ids)
                    ->map(fn ($id) => (int) $id)
                    ->contains($purchaseOrderId);
            })
            ->values();
    }

    protected function blockingPurchasesForOrder(int $businessId, int $purchaseOrderId, Collection $generatedPurchaseIds): Collection
    {
        $generatedPurchaseIdList = $generatedPurchaseIds->map(fn ($id) => (int) $id)->all();

        return Transaction::query()
            ->where('business_id', $businessId)
            ->where('type', 'purchase')
            ->when(! empty($generatedPurchaseIdList), fn ($query) => $query->whereNotIn('id', $generatedPurchaseIdList))
            ->orderByDesc('id')
            ->get()
            ->filter(function (Transaction $transaction) use ($purchaseOrderId) {
                return collect((array) $transaction->purchase_order_ids)
                    ->map(fn ($id) => (int) $id)
                    ->contains($purchaseOrderId);
            })
            ->values();
    }

    protected function purchaseReturnsForPurchase(int $businessId, int $purchaseId): Collection
    {
        return Transaction::query()
            ->where('business_id', $businessId)
            ->where('type', 'purchase_return')
            ->where('return_parent_id', $purchaseId)
            ->with(['purchase_lines', 'payment_lines'])
            ->orderByDesc('id')
            ->get();
    }

    protected function receiptDocumentsForOrder(int $businessId, int $purchaseOrderId, Collection $generatedPurchases): Collection
    {
        if (! Schema::hasTable('storage_documents')) {
            return collect();
        }

        $generatedPurchaseIds = $generatedPurchases->pluck('id')
            ->map(fn ($id) => (int) $id)
            ->filter()
            ->values()
            ->all();

        return StorageDocument::query()
            ->where('business_id', $businessId)
            ->where('document_type', 'receipt')
            ->where(function ($query) use ($purchaseOrderId, $generatedPurchaseIds) {
                $query->where(function ($subQuery) use ($purchaseOrderId) {
                    $subQuery->where('source_type', 'purchase_order')
                        ->where('source_id', $purchaseOrderId);
                });

                if (! empty($generatedPurchaseIds)) {
                    $query->orWhere(function ($subQuery) use ($generatedPurchaseIds) {
                        $subQuery->where('source_type', 'purchase')
                            ->whereIn('source_id', $generatedPurchaseIds);
                    });
                }
            })
            ->orderByDesc('id')
            ->get()
            ->filter(function (StorageDocument $document) use ($purchaseOrderId, $generatedPurchaseIds) {
                if ((string) $document->source_type === 'purchase_order' && (int) $document->source_id === $purchaseOrderId) {
                    return true;
                }

                if ((string) $document->source_type === 'purchase' && in_array((int) $document->source_id, $generatedPurchaseIds, true)) {
                    return true;
                }

                return (int) data_get((array) $document->meta, 'storage_manager.purchase_order_id', 0) === $purchaseOrderId;
            })
            ->values();
    }

    protected function putawayDocumentsForReceipts(int $businessId, Collection $receiptDocumentIds): Collection
    {
        if (! Schema::hasTable('storage_documents') || $receiptDocumentIds->isEmpty()) {
            return collect();
        }

        return StorageDocument::query()
            ->where('business_id', $businessId)
            ->where('document_type', 'putaway')
            ->whereIn('parent_document_id', $receiptDocumentIds->map(fn ($id) => (int) $id)->all())
            ->orderByDesc('id')
            ->get()
            ->values();
    }

    protected function deletePurchaseReturn(Transaction $purchaseReturn, int $businessId, int $userId, array &$summary): void
    {
        if (Schema::hasTable('vas_vouchers')) {
            $this->vasPostingService->queueSourceDocument('purchase_return', $purchaseReturn, [
                'is_deleted' => true,
                'source_snapshot' => $this->transactionSnapshot($purchaseReturn),
            ]);
        }

        foreach ($purchaseReturn->payment_lines as $payment) {
            TransactionPayment::deletePayment($payment);
            ++$summary['payments_deleted'];
        }

        if (empty($purchaseReturn->return_parent_id)) {
            foreach ($purchaseReturn->purchase_lines as $purchaseLine) {
                $this->productUtil->updateProductQuantity(
                    $purchaseReturn->location_id,
                    $purchaseLine->product_id,
                    $purchaseLine->variation_id,
                    $purchaseLine->quantity_returned,
                    0,
                    null,
                    false
                );
            }
        } else {
            $parentPurchase = Transaction::query()
                ->where('business_id', $businessId)
                ->where('type', 'purchase')
                ->with('purchase_lines')
                ->find($purchaseReturn->return_parent_id);

            if ($parentPurchase) {
                foreach ($parentPurchase->purchase_lines as $purchaseLine) {
                    $this->productUtil->updateProductQuantity(
                        $parentPurchase->location_id,
                        $purchaseLine->product_id,
                        $purchaseLine->variation_id,
                        $purchaseLine->quantity_returned,
                        0,
                        null,
                        false
                    );
                    $purchaseLine->quantity_returned = 0;
                    $purchaseLine->save();
                }
            }
        }

        PurchaseLine::query()
            ->where('transaction_id', $purchaseReturn->id)
            ->delete();
        AccountTransaction::query()
            ->where('transaction_id', $purchaseReturn->id)
            ->delete();
        $purchaseReturn->delete();

        ++$summary['purchase_returns_deleted'];
    }

    protected function deleteGeneratedPurchase(Transaction $purchase, int $businessId): void
    {
        $purchase->loadMissing('purchase_lines');

        foreach ($purchase->purchase_lines as $purchaseLine) {
            if (! empty($purchaseLine->purchase_order_line_id)) {
                $this->productUtil->updatePurchaseOrderLine($purchaseLine->purchase_order_line_id, 0, $purchaseLine->quantity);
            }
        }

        if ((string) $purchase->status === 'received') {
            foreach ($purchase->purchase_lines as $purchaseLine) {
                $this->productUtil->decreaseProductQuantity(
                    $purchaseLine->product_id,
                    $purchaseLine->variation_id,
                    $purchase->location_id,
                    $purchaseLine->quantity
                );
            }

            $this->transactionUtil->adjustMappingPurchaseSellAfterEditingPurchase('received', $purchase, $purchase->purchase_lines);
        }

        $logProperties = [
            'id' => $purchase->id,
            'ref_no' => $purchase->ref_no,
        ];
        $this->transactionUtil->activityLog($purchase, 'purchase_deleted', $logProperties);

        PurchaseCreatedOrModified::dispatch($purchase, true);

        PurchaseLine::query()
            ->where('transaction_id', $purchase->id)
            ->delete();
        AccountTransaction::query()
            ->where('transaction_id', $purchase->id)
            ->delete();
        $purchase->delete();

        $this->transactionUtil->updatePurchaseOrderStatus((array) $purchase->purchase_order_ids);
    }

    protected function deleteStorageDocumentCascade(int $businessId, StorageDocument $document): void
    {
        if ((int) $document->business_id !== $businessId) {
            throw new RuntimeException('Storage document does not belong to the current business.');
        }

        $lineIds = [];
        if (Schema::hasTable('storage_document_lines')) {
            $lineIds = StorageDocumentLine::query()
                ->where('business_id', $businessId)
                ->where('document_id', $document->id)
                ->pluck('id')
                ->map(fn ($id) => (int) $id)
                ->all();
        }

        $taskIds = [];
        if (Schema::hasTable('storage_tasks')) {
            $taskIds = StorageTask::query()
                ->where('business_id', $businessId)
                ->where('document_id', $document->id)
                ->pluck('id')
                ->map(fn ($id) => (int) $id)
                ->all();
        }

        if (! empty($taskIds) && Schema::hasTable('storage_task_events')) {
            StorageTaskEvent::query()
                ->where('business_id', $businessId)
                ->whereIn('task_id', $taskIds)
                ->delete();
        }

        if (Schema::hasTable('storage_approval_requests')) {
            StorageApprovalRequest::query()
                ->where('business_id', $businessId)
                ->where(function ($query) use ($document, $lineIds) {
                    $query->where('document_id', $document->id);
                    if (! empty($lineIds)) {
                        $query->orWhereIn('document_line_id', $lineIds);
                    }
                })
                ->delete();
        }

        if (! empty($taskIds) && Schema::hasTable('storage_inventory_movements')) {
            StorageInventoryMovement::query()
                ->where('business_id', $businessId)
                ->where(function ($query) use ($document, $lineIds, $taskIds) {
                    $query->where('document_id', $document->id)
                        ->orWhereIn('task_id', $taskIds);
                    if (! empty($lineIds)) {
                        $query->orWhereIn('document_line_id', $lineIds);
                    }
                })
                ->delete();
        } elseif (Schema::hasTable('storage_inventory_movements')) {
            StorageInventoryMovement::query()
                ->where('business_id', $businessId)
                ->where('document_id', $document->id)
                ->delete();
        }

        if (Schema::hasTable('storage_tasks')) {
            StorageTask::query()
                ->where('business_id', $businessId)
                ->where('document_id', $document->id)
                ->delete();
        }

        if (Schema::hasTable('storage_document_lines')) {
            StorageDocumentLine::query()
                ->where('business_id', $businessId)
                ->where('document_id', $document->id)
                ->delete();
        }

        if (Schema::hasTable('storage_document_links')) {
            StorageDocumentLink::query()
                ->where('business_id', $businessId)
                ->where('document_id', $document->id)
                ->delete();
        }

        if (Schema::hasTable('storage_sync_logs')) {
            StorageSyncLog::query()
                ->where('business_id', $businessId)
                ->where('document_id', $document->id)
                ->delete();
        }

        $document->delete();
    }

    protected function requiresVasUnlink(StorageDocument $document): bool
    {
        $hasLink = false;
        if (Schema::hasTable('storage_document_links')) {
            $hasLink = StorageDocumentLink::query()
                ->where('business_id', $document->business_id)
                ->where('document_id', $document->id)
                ->where('linked_system', 'vas')
                ->exists();
        }

        return ! empty($document->vas_inventory_document_id)
            || (string) $document->sync_status === 'posted'
            || $hasLink;
    }

    protected function isGeneratedPurchaseOrderReceipt(StorageDocument $document): bool
    {
        return (bool) data_get((array) $document->meta, 'storage_manager.generated_from_purchase_order', false);
    }

    protected function transactionSnapshot(Transaction $transaction): array
    {
        return [
            'id' => (int) $transaction->id,
            'business_id' => (int) $transaction->business_id,
            'location_id' => (int) ($transaction->location_id ?? 0),
            'contact_id' => (int) ($transaction->contact_id ?? 0),
            'transaction_date' => $transaction->transaction_date,
            'ref_no' => $transaction->ref_no,
            'invoice_no' => $transaction->invoice_no,
            'status' => $transaction->status,
            'final_total' => (float) ($transaction->final_total ?? 0),
            'tax_amount' => (float) ($transaction->tax_amount ?? 0),
            'created_by' => (int) ($transaction->created_by ?? 0),
            'type' => (string) $transaction->type,
        ];
    }

    protected function summaryMessage(array $summary): string
    {
        $parts = ['Purchase order deleted successfully.'];

        if ($summary['putaways_reopened'] > 0) {
            $parts[] = $summary['putaways_reopened'] . ' putaway reversed';
        }
        if ($summary['receipts_reopened'] > 0) {
            $parts[] = $summary['receipts_reopened'] . ' receipt reversed';
        }
        if ($summary['storage_documents_deleted'] > 0) {
            $parts[] = $summary['storage_documents_deleted'] . ' storage document deleted';
        }
        if ($summary['purchase_returns_deleted'] > 0) {
            $parts[] = $summary['purchase_returns_deleted'] . ' purchase return deleted';
        }
        if ($summary['payments_deleted'] > 0) {
            $parts[] = $summary['payments_deleted'] . ' payment deleted';
        }
        if ($summary['generated_purchases_deleted'] > 0) {
            $parts[] = $summary['generated_purchases_deleted'] . ' generated purchase deleted';
        }
        if ($summary['vas_links_removed'] > 0) {
            $parts[] = $summary['vas_links_removed'] . ' VAS link removed';
        }

        return implode(' ', $parts);
    }
}
