<?php

use Modules\VasAccounting\Http\Controllers\ChartOfAccountsController;
use Modules\VasAccounting\Http\Controllers\BudgetController;
use Modules\VasAccounting\Http\Controllers\CashBankController;
use Modules\VasAccounting\Http\Controllers\ClosingController;
use Modules\VasAccounting\Http\Controllers\ContractController;
use Modules\VasAccounting\Http\Controllers\CostingController;
use Modules\VasAccounting\Http\Controllers\CutoverController;
use Modules\VasAccounting\Http\Controllers\DashboardController;
use Modules\VasAccounting\Http\Controllers\EInvoiceController;
use Modules\VasAccounting\Http\Controllers\ExpenseController;
use Modules\VasAccounting\Http\Controllers\FixedAssetController;
use Modules\VasAccounting\Http\Controllers\IntegrationController;
use Modules\VasAccounting\Http\Controllers\InventoryController;
use Modules\VasAccounting\Http\Controllers\InvoiceController;
use Modules\VasAccounting\Http\Controllers\LoanController;
use Modules\VasAccounting\Http\Controllers\PayableController;
use Modules\VasAccounting\Http\Controllers\PaymentDocumentController;
use Modules\VasAccounting\Http\Controllers\PayrollController;
use Modules\VasAccounting\Http\Controllers\PeriodController;
use Modules\VasAccounting\Http\Controllers\ProcurementController;
use Modules\VasAccounting\Http\Controllers\ReceivableController;
use Modules\VasAccounting\Http\Controllers\ReportController;
use Modules\VasAccounting\Http\Controllers\SetupController;
use Modules\VasAccounting\Http\Controllers\TaxController;
use Modules\VasAccounting\Http\Controllers\ToolsController;
use Modules\VasAccounting\Http\Controllers\VoucherController;
use Modules\VasAccounting\Http\Middleware\ApplyVasLocale;

Route::middleware(['web', 'auth', 'SetSessionData', 'language', ApplyVasLocale::class, 'timezone', 'AdminSidebarMenu'])->group(function () {
    Route::prefix('vas-accounting')->name('vasaccounting.')->group(function () {
        Route::get('/setup', [SetupController::class, 'index'])->name('setup.index');
        Route::post('/setup', [SetupController::class, 'store'])->name('setup.store');
        Route::post('/setup/bootstrap', [SetupController::class, 'bootstrap'])->name('setup.bootstrap');

        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
        Route::prefix('ui')->name('ui.')->group(function () {
            Route::get('/dashboard/kpis', [DashboardController::class, 'kpis'])->name('dashboard.kpis');
            Route::get('/dashboard/trends', [DashboardController::class, 'trends'])->name('dashboard.trends');
            Route::get('/dashboard/failures', [DashboardController::class, 'failures'])->name('dashboard.failures');
            Route::get('/reports/{reportKey}/datatable', [ReportController::class, 'datatable'])->name('reports.datatable');
        });

        Route::get('/chart-of-accounts', [ChartOfAccountsController::class, 'index'])->name('chart.index');
        Route::post('/chart-of-accounts', [ChartOfAccountsController::class, 'store'])->name('chart.store');

        Route::get('/periods', [PeriodController::class, 'index'])->name('periods.index');
        Route::post('/periods', [PeriodController::class, 'store'])->name('periods.store');
        Route::post('/periods/{period}/close', [PeriodController::class, 'close'])->whereNumber('period')->name('periods.close');

        Route::get('/vouchers', [VoucherController::class, 'index'])->name('vouchers.index');
        Route::get('/vouchers/create', [VoucherController::class, 'create'])->name('vouchers.create');
        Route::post('/vouchers', [VoucherController::class, 'store'])->name('vouchers.store');
        Route::get('/vouchers/{voucher}', [VoucherController::class, 'show'])->whereNumber('voucher')->name('vouchers.show');
        Route::post('/vouchers/{voucher}/post', [VoucherController::class, 'post'])->whereNumber('voucher')->name('vouchers.post');
        Route::post('/vouchers/{voucher}/reverse', [VoucherController::class, 'reverse'])->whereNumber('voucher')->name('vouchers.reverse');
        Route::delete('/vouchers/{voucher}', [VoucherController::class, 'destroy'])->whereNumber('voucher')->name('vouchers.destroy');

        Route::get('/cash-bank', [CashBankController::class, 'index'])->name('cash_bank.index');
        Route::post('/cash-bank/treasury-documents', [CashBankController::class, 'storeTreasuryDocument'])->name('cash_bank.treasury_documents.store');
        Route::post('/cash-bank/treasury-documents/{document}/submit', [CashBankController::class, 'submitTreasuryDocument'])->whereNumber('document')->name('cash_bank.treasury_documents.submit');
        Route::post('/cash-bank/treasury-documents/{document}/approve', [CashBankController::class, 'approveTreasuryDocument'])->whereNumber('document')->name('cash_bank.treasury_documents.approve');
        Route::post('/cash-bank/treasury-documents/{document}/post', [CashBankController::class, 'postTreasuryDocument'])->whereNumber('document')->name('cash_bank.treasury_documents.post');
        Route::post('/cash-bank/treasury-documents/{document}/reverse', [CashBankController::class, 'reverseTreasuryDocument'])->whereNumber('document')->name('cash_bank.treasury_documents.reverse');
        Route::post('/cash-bank/cashbooks', [CashBankController::class, 'storeCashbook'])->name('cash_bank.cashbooks.store');
        Route::post('/cash-bank/bank-accounts', [CashBankController::class, 'storeBankAccount'])->name('cash_bank.bank_accounts.store');
        Route::post('/cash-bank/statements', [CashBankController::class, 'importStatement'])->name('cash_bank.statements.import');
        Route::post('/cash-bank/statements/lines/{line}/reconcile', [CashBankController::class, 'reconcileLine'])->whereNumber('line')->name('cash_bank.statements.reconcile');
        Route::post('/cash-bank/statements/lines/{line}/canonical-reconcile', [CashBankController::class, 'reconcileLineCanonically'])->whereNumber('line')->name('cash_bank.statements.canonical_reconcile');
        Route::post('/cash-bank/statements/lines/{line}/refresh-exception', [CashBankController::class, 'refreshTreasuryException'])->whereNumber('line')->name('cash_bank.statements.refresh_exception');
        Route::post('/cash-bank/statements/lines/{line}/ignore-exception', [CashBankController::class, 'ignoreTreasuryException'])->whereNumber('line')->name('cash_bank.statements.ignore_exception');
        Route::post('/cash-bank/reconciliations/{reconciliation}/reverse', [CashBankController::class, 'reverseCanonicalReconciliation'])->whereNumber('reconciliation')->name('cash_bank.reconciliations.reverse');
        Route::prefix('payment-documents')->name('payment_documents.')->group(function () {
            Route::get('/', [PaymentDocumentController::class, 'index'])->name('index');
            Route::get('/create', [PaymentDocumentController::class, 'create'])->name('create');
            Route::post('/', [PaymentDocumentController::class, 'store'])->name('store');
            Route::get('/{voucher}', [PaymentDocumentController::class, 'show'])->whereNumber('voucher')->name('show');
            Route::get('/{voucher}/edit', [PaymentDocumentController::class, 'edit'])->whereNumber('voucher')->name('edit');
            Route::put('/{voucher}', [PaymentDocumentController::class, 'update'])->whereNumber('voucher')->name('update');
            Route::post('/{voucher}/submit', [PaymentDocumentController::class, 'submit'])->whereNumber('voucher')->name('submit');
            Route::post('/{voucher}/approve', [PaymentDocumentController::class, 'approve'])->whereNumber('voucher')->name('approve');
            Route::post('/{voucher}/reject', [PaymentDocumentController::class, 'reject'])->whereNumber('voucher')->name('reject');
            Route::post('/{voucher}/cancel', [PaymentDocumentController::class, 'cancel'])->whereNumber('voucher')->name('cancel');
            Route::post('/{voucher}/post', [PaymentDocumentController::class, 'post'])->whereNumber('voucher')->name('post');
            Route::post('/{voucher}/reverse', [PaymentDocumentController::class, 'reverse'])->whereNumber('voucher')->name('reverse');
        });
        Route::get('/receivables', [ReceivableController::class, 'index'])->name('receivables.index');
        Route::post('/receivables/allocations', [ReceivableController::class, 'storeAllocation'])->name('receivables.allocations.store');
        Route::get('/procurement', [ProcurementController::class, 'index'])->name('procurement.index');
        Route::post('/procurement', [ProcurementController::class, 'store'])->name('procurement.store');
        Route::post('/procurement/{document}/submit', [ProcurementController::class, 'submit'])->whereNumber('document')->name('procurement.submit');
        Route::post('/procurement/{document}/approve', [ProcurementController::class, 'approve'])->whereNumber('document')->name('procurement.approve');
        Route::post('/procurement/{document}/reject', [ProcurementController::class, 'reject'])->whereNumber('document')->name('procurement.reject');
        Route::post('/procurement/{document}/fulfill', [ProcurementController::class, 'fulfill'])->whereNumber('document')->name('procurement.fulfill');
        Route::post('/procurement/{document}/match', [ProcurementController::class, 'match'])->whereNumber('document')->name('procurement.match');
        Route::post('/procurement/discrepancies/{exception}/take-ownership', [ProcurementController::class, 'takeOwnership'])->whereNumber('exception')->name('procurement.discrepancies.take_ownership');
        Route::post('/procurement/discrepancies/{exception}/assign', [ProcurementController::class, 'assignDiscrepancy'])->whereNumber('exception')->name('procurement.discrepancies.assign');
        Route::post('/procurement/discrepancies/{exception}/resolve', [ProcurementController::class, 'resolveDiscrepancy'])->whereNumber('exception')->name('procurement.discrepancies.resolve');
        Route::post('/procurement/{document}/post', [ProcurementController::class, 'post'])->whereNumber('document')->name('procurement.post');
        Route::post('/procurement/{document}/close', [ProcurementController::class, 'close'])->whereNumber('document')->name('procurement.close');
        Route::post('/procurement/{document}/reverse', [ProcurementController::class, 'reverse'])->whereNumber('document')->name('procurement.reverse');
        Route::get('/payables', [PayableController::class, 'index'])->name('payables.index');
        Route::post('/payables/allocations', [PayableController::class, 'storeAllocation'])->name('payables.allocations.store');
        Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');
        Route::get('/invoices/create', [InvoiceController::class, 'create'])->name('invoices.create');
        Route::post('/invoices', [InvoiceController::class, 'store'])->name('invoices.store');
        Route::get('/invoices/{voucher}', [InvoiceController::class, 'show'])->whereNumber('voucher')->name('invoices.show');
        Route::get('/invoices/{voucher}/edit', [InvoiceController::class, 'edit'])->whereNumber('voucher')->name('invoices.edit');
        Route::put('/invoices/{voucher}', [InvoiceController::class, 'update'])->whereNumber('voucher')->name('invoices.update');
        Route::post('/invoices/{voucher}/submit', [InvoiceController::class, 'submit'])->whereNumber('voucher')->name('invoices.submit');
        Route::post('/invoices/{voucher}/approve', [InvoiceController::class, 'approve'])->whereNumber('voucher')->name('invoices.approve');
        Route::post('/invoices/{voucher}/reject', [InvoiceController::class, 'reject'])->whereNumber('voucher')->name('invoices.reject');
        Route::post('/invoices/{voucher}/cancel', [InvoiceController::class, 'cancel'])->whereNumber('voucher')->name('invoices.cancel');
        Route::post('/invoices/{voucher}/post', [InvoiceController::class, 'post'])->whereNumber('voucher')->name('invoices.post');
        Route::post('/invoices/{voucher}/reverse', [InvoiceController::class, 'reverse'])->whereNumber('voucher')->name('invoices.reverse');
        Route::get('/inventory', [InventoryController::class, 'index'])->name('inventory.index');
        Route::post('/inventory/warehouses', [InventoryController::class, 'storeWarehouse'])->name('inventory.warehouses.store');
        Route::post('/inventory/documents', [InventoryController::class, 'storeDocument'])->name('inventory.documents.store');
        Route::get('/inventory/documents/{document}', [InventoryController::class, 'showDocument'])->whereNumber('document')->name('inventory.documents.show');
        Route::post('/inventory/documents/{document}/post', [InventoryController::class, 'postDocument'])->whereNumber('document')->name('inventory.documents.post');
        Route::post('/inventory/documents/{document}/reverse', [InventoryController::class, 'reverseDocument'])->whereNumber('document')->name('inventory.documents.reverse');
        Route::delete('/inventory/documents/{document}', [InventoryController::class, 'destroyDocument'])->whereNumber('document')->name('inventory.documents.destroy');
        Route::get('/expenses', [ExpenseController::class, 'index'])->name('expenses.index');
        Route::post('/expenses', [ExpenseController::class, 'store'])->name('expenses.store');
        Route::post('/expenses/{document}/submit', [ExpenseController::class, 'submit'])->whereNumber('document')->name('expenses.submit');
        Route::post('/expenses/{document}/approve', [ExpenseController::class, 'approve'])->whereNumber('document')->name('expenses.approve');
        Route::post('/expenses/{document}/reject', [ExpenseController::class, 'reject'])->whereNumber('document')->name('expenses.reject');
        Route::post('/expenses/{document}/escalate', [ExpenseController::class, 'escalate'])->whereNumber('document')->name('expenses.escalate');
        Route::post('/expenses/{document}/retry-escalation-dispatch', [ExpenseController::class, 'retryEscalationDispatch'])->whereNumber('document')->name('expenses.retry_escalation_dispatch');
        Route::post('/expenses/{document}/post', [ExpenseController::class, 'post'])->whereNumber('document')->name('expenses.post');
        Route::post('/expenses/{document}/reverse', [ExpenseController::class, 'reverse'])->whereNumber('document')->name('expenses.reverse');
        Route::get('/tools', [ToolsController::class, 'index'])->name('tools.index');
        Route::post('/tools', [ToolsController::class, 'store'])->name('tools.store');
        Route::post('/tools/amortization/run', [ToolsController::class, 'runAmortization'])->name('tools.amortization.run');
        Route::get('/fixed-assets', [FixedAssetController::class, 'index'])->name('assets.index');
        Route::post('/fixed-assets/categories', [FixedAssetController::class, 'storeCategory'])->name('assets.categories.store');
        Route::post('/fixed-assets', [FixedAssetController::class, 'storeAsset'])->name('assets.store');
        Route::post('/fixed-assets/{asset}/transfer', [FixedAssetController::class, 'transfer'])->whereNumber('asset')->name('assets.transfer');
        Route::post('/fixed-assets/{asset}/dispose', [FixedAssetController::class, 'dispose'])->whereNumber('asset')->name('assets.dispose');
        Route::post('/fixed-assets/depreciation/run', [FixedAssetController::class, 'runDepreciation'])->name('assets.depreciation.run');
        Route::get('/tax', [TaxController::class, 'index'])->name('tax.index');
        Route::post('/tax/export', [TaxController::class, 'export'])->name('tax.export');
        Route::get('/e-invoices', [EInvoiceController::class, 'index'])->name('einvoices.index');
        Route::post('/e-invoices/{voucher}/issue', [EInvoiceController::class, 'issue'])->whereNumber('voucher')->name('einvoices.issue');
        Route::post('/e-invoices/{document}/sync', [EInvoiceController::class, 'sync'])->whereNumber('document')->name('einvoices.sync');
        Route::post('/e-invoices/{document}/cancel', [EInvoiceController::class, 'cancel'])->whereNumber('document')->name('einvoices.cancel');
        Route::post('/e-invoices/{document}/correct', [EInvoiceController::class, 'correct'])->whereNumber('document')->name('einvoices.correct');
        Route::post('/e-invoices/{document}/replace', [EInvoiceController::class, 'replace'])->whereNumber('document')->name('einvoices.replace');
        Route::get('/payroll', [PayrollController::class, 'index'])->name('payroll.index');
        Route::post('/payroll/bridge', [PayrollController::class, 'bridgeGroup'])->name('payroll.bridge');
        Route::post('/payroll/bridge-payments', [PayrollController::class, 'bridgePayments'])->name('payroll.bridge_payments');
        Route::get('/contracts', [ContractController::class, 'index'])->name('contracts.index');
        Route::post('/contracts', [ContractController::class, 'store'])->name('contracts.store');
        Route::post('/contracts/milestones', [ContractController::class, 'storeMilestone'])->name('contracts.milestones.store');
        Route::post('/contracts/milestones/{milestone}/post', [ContractController::class, 'postMilestone'])->whereNumber('milestone')->name('contracts.milestones.post');
        Route::get('/loans', [LoanController::class, 'index'])->name('loans.index');
        Route::post('/loans', [LoanController::class, 'store'])->name('loans.store');
        Route::post('/loans/{loan}/disburse', [LoanController::class, 'disburse'])->whereNumber('loan')->name('loans.disburse');
        Route::post('/loans/schedules', [LoanController::class, 'storeSchedule'])->name('loans.schedules.store');
        Route::post('/loans/schedules/{schedule}/settle', [LoanController::class, 'settleSchedule'])->whereNumber('schedule')->name('loans.schedules.settle');
        Route::get('/costing', [CostingController::class, 'index'])->name('costing.index');
        Route::post('/costing/departments', [CostingController::class, 'storeDepartment'])->name('costing.departments.store');
        Route::post('/costing/cost-centers', [CostingController::class, 'storeCostCenter'])->name('costing.cost_centers.store');
        Route::post('/costing/projects', [CostingController::class, 'storeProject'])->name('costing.projects.store');
        Route::get('/budgets', [BudgetController::class, 'index'])->name('budgets.index');
        Route::post('/budgets', [BudgetController::class, 'store'])->name('budgets.store');
        Route::post('/budgets/lines', [BudgetController::class, 'storeLine'])->name('budgets.lines.store');
        Route::post('/budgets/{budget}/sync-actuals', [BudgetController::class, 'syncActuals'])->whereNumber('budget')->name('budgets.sync_actuals');
        Route::get('/integrations', [IntegrationController::class, 'index'])->name('integrations.index');
        Route::post('/integrations/runs', [IntegrationController::class, 'storeRun'])->name('integrations.runs.store');
        Route::post('/integrations/failures/{failure}/retry', [IntegrationController::class, 'retryFailure'])->whereNumber('failure')->name('integrations.failures.retry');

        Route::get('/closing', [ClosingController::class, 'index'])->name('closing.index');
        Route::post('/closing/period/{period}/soft-lock', [ClosingController::class, 'softLock'])->whereNumber('period')->name('closing.soft_lock');
        Route::post('/closing/period/{period}', [ClosingController::class, 'close'])->whereNumber('period')->name('closing.close');
        Route::post('/closing/period/{period}/reopen', [ClosingController::class, 'reopen'])->whereNumber('period')->name('closing.reopen');
        Route::post('/closing/period/{period}/packet', [ClosingController::class, 'packet'])->whereNumber('period')->name('closing.packet');
        Route::post('/closing/period/{period}/procurement-discrepancies/assign-unassigned', [ClosingController::class, 'assignUnassignedProcurementDiscrepancies'])->whereNumber('period')->name('closing.procurement_discrepancies.assign_unassigned');
        Route::post('/closing/period/{period}/procurement-discrepancies/assign-unassigned-to-me', [ClosingController::class, 'assignUnassignedProcurementDiscrepanciesToMe'])->whereNumber('period')->name('closing.procurement_discrepancies.assign_unassigned_to_me');
        Route::post('/closing/period/{period}/procurement-discrepancies/{exception}/assign', [ClosingController::class, 'assignProcurementDiscrepancy'])->whereNumber('period')->whereNumber('exception')->name('closing.procurement_discrepancies.assign');

        Route::prefix('cutover')->name('cutover.')->group(function () {
            Route::get('/', [CutoverController::class, 'index'])->name('index');
            Route::post('/settings', [CutoverController::class, 'updateSettings'])->name('settings.update');
            Route::post('/personas/{persona}', [CutoverController::class, 'updatePersona'])->name('personas.update');
        });

        Route::prefix('reports')->name('reports.')->group(function () {
            Route::get('/', [ReportController::class, 'index'])->name('index');
            Route::post('/snapshots', [ReportController::class, 'storeSnapshot'])->name('snapshots.store');
            Route::get('/snapshots/{snapshot}', [ReportController::class, 'showSnapshot'])->whereNumber('snapshot')->name('snapshots.show');
            Route::get('/trial-balance', [ReportController::class, 'trialBalance'])->name('trial_balance');
            Route::get('/general-ledger', [ReportController::class, 'generalLedger'])->name('general_ledger');
            Route::get('/vat', [ReportController::class, 'vat'])->name('vat');
            Route::get('/cash-book', [ReportController::class, 'cashBook'])->name('cash_book');
            Route::get('/bank-book', [ReportController::class, 'bankBook'])->name('bank_book');
            Route::get('/bank-reconciliation', [ReportController::class, 'bankReconciliation'])->name('bank_reconciliation');
            Route::get('/receivables', [ReportController::class, 'receivables'])->name('receivables');
            Route::get('/payables', [ReportController::class, 'payables'])->name('payables');
            Route::get('/invoice-register', [ReportController::class, 'invoiceRegister'])->name('invoice_register');
            Route::get('/purchase-register', [ReportController::class, 'purchaseRegister'])->name('purchase_register');
            Route::get('/goods-receipt-register', [ReportController::class, 'goodsReceiptRegister'])->name('goods_receipt_register');
            Route::get('/procurement-discrepancies', [ReportController::class, 'procurementDiscrepancies'])->name('procurement_discrepancies');
            Route::get('/procurement-discrepancy-ownership', [ReportController::class, 'procurementDiscrepancyOwnership'])->name('procurement_discrepancy_ownership');
            Route::post('/procurement-discrepancy-ownership/assign-unassigned', [ReportController::class, 'assignUnassignedProcurementDiscrepancies'])->name('procurement_discrepancy_ownership.assign_unassigned');
            Route::post('/procurement-discrepancy-ownership/assign-unassigned-to-me', [ReportController::class, 'assignUnassignedProcurementDiscrepanciesToMe'])->name('procurement_discrepancy_ownership.assign_unassigned_to_me');
            Route::get('/procurement-aging', [ReportController::class, 'procurementAging'])->name('procurement_aging');
            Route::get('/expense-outstanding', [ReportController::class, 'expenseOutstanding'])->name('expense_outstanding');
            Route::get('/expense-register', [ReportController::class, 'expenseRegister'])->name('expense_register');
            Route::get('/expense-escalation-audit', [ReportController::class, 'expenseEscalationAudit'])->name('expense_escalation_audit');
            Route::post('/expense-escalation-audit/retry-failed-dispatches', [ReportController::class, 'retryFailedExpenseEscalationDispatches'])->name('expense_escalation_audit.retry_failed_dispatches');
            Route::get('/inventory', [ReportController::class, 'inventory'])->name('inventory');
            Route::get('/fixed-assets', [ReportController::class, 'fixedAssets'])->name('fixed_assets');
            Route::get('/payroll-bridge', [ReportController::class, 'payrollBridge'])->name('payroll_bridge');
            Route::get('/contracts', [ReportController::class, 'contracts'])->name('contracts');
            Route::get('/loans', [ReportController::class, 'loans'])->name('loans');
            Route::get('/costing', [ReportController::class, 'costing'])->name('costing');
            Route::get('/budget-variance', [ReportController::class, 'budgetVariance'])->name('budget_variance');
            Route::get('/financial-statements', [ReportController::class, 'financialStatements'])->name('financial_statements');
            Route::get('/close-packet', [ReportController::class, 'closePacket'])->name('close_packet');
            Route::get('/operational-health', [ReportController::class, 'operationalHealth'])->name('operational_health');
        });
    });
});
