<?php

namespace Modules\VasAccounting\Tests\Feature;

use Modules\VasAccounting\Http\Middleware\RedirectLegacyAccountingToVas;
use Tests\TestCase;

class VasAccountingRoutesRegistrationTest extends TestCase
{
    public function test_vas_accounting_named_routes_are_registered(): void
    {
        $router = app('router');

        $this->assertTrue($router->has('vasaccounting.setup.index'));
        $this->assertTrue($router->has('vasaccounting.dashboard.index'));
        $this->assertTrue($router->has('vasaccounting.ui.dashboard.kpis'));
        $this->assertTrue($router->has('vasaccounting.ui.dashboard.trends'));
        $this->assertTrue($router->has('vasaccounting.ui.dashboard.failures'));
        $this->assertTrue($router->has('vasaccounting.ui.reports.datatable'));
        $this->assertTrue($router->has('vasaccounting.chart.index'));
        $this->assertTrue($router->has('vasaccounting.periods.index'));
        $this->assertTrue($router->has('vasaccounting.vouchers.index'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.index'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.treasury_documents.store'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.treasury_documents.submit'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.treasury_documents.approve'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.treasury_documents.post'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.treasury_documents.reverse'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.cashbooks.store'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.bank_accounts.store'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.statements.import'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.statements.reconcile'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.statements.canonical_reconcile'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.statements.refresh_exception'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.statements.ignore_exception'));
        $this->assertTrue($router->has('vasaccounting.cash_bank.reconciliations.reverse'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.index'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.create'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.store'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.show'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.edit'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.update'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.submit'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.approve'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.reject'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.cancel'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.post'));
        $this->assertTrue($router->has('vasaccounting.payment_documents.reverse'));
        $this->assertTrue($router->has('vasaccounting.receivables.index'));
        $this->assertTrue($router->has('vasaccounting.receivables.allocations.store'));
        $this->assertTrue($router->has('vasaccounting.procurement.index'));
        $this->assertTrue($router->has('vasaccounting.procurement.store'));
        $this->assertTrue($router->has('vasaccounting.procurement.submit'));
        $this->assertTrue($router->has('vasaccounting.procurement.approve'));
        $this->assertTrue($router->has('vasaccounting.procurement.reject'));
        $this->assertTrue($router->has('vasaccounting.procurement.fulfill'));
        $this->assertTrue($router->has('vasaccounting.procurement.match'));
        $this->assertTrue($router->has('vasaccounting.procurement.discrepancies.take_ownership'));
        $this->assertTrue($router->has('vasaccounting.procurement.discrepancies.assign'));
        $this->assertTrue($router->has('vasaccounting.procurement.discrepancies.resolve'));
        $this->assertTrue($router->has('vasaccounting.procurement.post'));
        $this->assertTrue($router->has('vasaccounting.procurement.close'));
        $this->assertTrue($router->has('vasaccounting.procurement.reverse'));
        $this->assertTrue($router->has('vasaccounting.payables.index'));
        $this->assertTrue($router->has('vasaccounting.payables.allocations.store'));
        $this->assertTrue($router->has('vasaccounting.invoices.index'));
        $this->assertTrue($router->has('vasaccounting.invoices.create'));
        $this->assertTrue($router->has('vasaccounting.invoices.store'));
        $this->assertTrue($router->has('vasaccounting.invoices.show'));
        $this->assertTrue($router->has('vasaccounting.invoices.edit'));
        $this->assertTrue($router->has('vasaccounting.invoices.update'));
        $this->assertTrue($router->has('vasaccounting.invoices.submit'));
        $this->assertTrue($router->has('vasaccounting.invoices.approve'));
        $this->assertTrue($router->has('vasaccounting.invoices.reject'));
        $this->assertTrue($router->has('vasaccounting.invoices.cancel'));
        $this->assertTrue($router->has('vasaccounting.invoices.post'));
        $this->assertTrue($router->has('vasaccounting.invoices.reverse'));
        $this->assertTrue($router->has('vasaccounting.inventory.index'));
        $this->assertTrue($router->has('vasaccounting.inventory.warehouses.store'));
        $this->assertTrue($router->has('vasaccounting.inventory.documents.store'));
        $this->assertTrue($router->has('vasaccounting.inventory.documents.post'));
        $this->assertTrue($router->has('vasaccounting.inventory.documents.reverse'));
        $this->assertTrue($router->has('vasaccounting.expenses.index'));
        $this->assertTrue($router->has('vasaccounting.expenses.store'));
        $this->assertTrue($router->has('vasaccounting.expenses.submit'));
        $this->assertTrue($router->has('vasaccounting.expenses.approve'));
        $this->assertTrue($router->has('vasaccounting.expenses.reject'));
        $this->assertTrue($router->has('vasaccounting.expenses.escalate'));
        $this->assertTrue($router->has('vasaccounting.expenses.retry_escalation_dispatch'));
        $this->assertTrue($router->has('vasaccounting.expenses.post'));
        $this->assertTrue($router->has('vasaccounting.expenses.reverse'));
        $this->assertTrue($router->has('vasaccounting.tools.index'));
        $this->assertTrue($router->has('vasaccounting.tools.store'));
        $this->assertTrue($router->has('vasaccounting.tools.amortization.run'));
        $this->assertTrue($router->has('vasaccounting.assets.index'));
        $this->assertTrue($router->has('vasaccounting.assets.categories.store'));
        $this->assertTrue($router->has('vasaccounting.assets.store'));
        $this->assertTrue($router->has('vasaccounting.assets.transfer'));
        $this->assertTrue($router->has('vasaccounting.assets.dispose'));
        $this->assertTrue($router->has('vasaccounting.tax.index'));
        $this->assertTrue($router->has('vasaccounting.tax.export'));
        $this->assertTrue($router->has('vasaccounting.einvoices.index'));
        $this->assertTrue($router->has('vasaccounting.einvoices.cancel'));
        $this->assertTrue($router->has('vasaccounting.einvoices.correct'));
        $this->assertTrue($router->has('vasaccounting.einvoices.replace'));
        $this->assertTrue($router->has('vasaccounting.payroll.index'));
        $this->assertTrue($router->has('vasaccounting.payroll.bridge'));
        $this->assertTrue($router->has('vasaccounting.payroll.bridge_payments'));
        $this->assertTrue($router->has('vasaccounting.contracts.index'));
        $this->assertTrue($router->has('vasaccounting.contracts.store'));
        $this->assertTrue($router->has('vasaccounting.contracts.milestones.store'));
        $this->assertTrue($router->has('vasaccounting.contracts.milestones.post'));
        $this->assertTrue($router->has('vasaccounting.loans.index'));
        $this->assertTrue($router->has('vasaccounting.loans.store'));
        $this->assertTrue($router->has('vasaccounting.loans.disburse'));
        $this->assertTrue($router->has('vasaccounting.loans.schedules.store'));
        $this->assertTrue($router->has('vasaccounting.loans.schedules.settle'));
        $this->assertTrue($router->has('vasaccounting.costing.index'));
        $this->assertTrue($router->has('vasaccounting.costing.departments.store'));
        $this->assertTrue($router->has('vasaccounting.costing.cost_centers.store'));
        $this->assertTrue($router->has('vasaccounting.costing.projects.store'));
        $this->assertTrue($router->has('vasaccounting.budgets.index'));
        $this->assertTrue($router->has('vasaccounting.budgets.store'));
        $this->assertTrue($router->has('vasaccounting.budgets.lines.store'));
        $this->assertTrue($router->has('vasaccounting.budgets.sync_actuals'));
        $this->assertTrue($router->has('vasaccounting.integrations.index'));
        $this->assertTrue($router->has('vasaccounting.integrations.runs.store'));
        $this->assertTrue($router->has('vasaccounting.integrations.failures.retry'));
        $this->assertTrue($router->has('vasaccounting.closing.index'));
        $this->assertTrue($router->has('vasaccounting.closing.soft_lock'));
        $this->assertTrue($router->has('vasaccounting.closing.reopen'));
        $this->assertTrue($router->has('vasaccounting.closing.packet'));
        $this->assertTrue($router->has('vasaccounting.closing.procurement_discrepancies.assign_unassigned'));
        $this->assertTrue($router->has('vasaccounting.closing.procurement_discrepancies.assign_unassigned_to_me'));
        $this->assertTrue($router->has('vasaccounting.closing.procurement_discrepancies.assign'));
        $this->assertTrue($router->has('vasaccounting.cutover.index'));
        $this->assertTrue($router->has('vasaccounting.cutover.settings.update'));
        $this->assertTrue($router->has('vasaccounting.cutover.personas.update'));
        $this->assertTrue($router->has('vasaccounting.reports.index'));
        $this->assertTrue($router->has('vasaccounting.reports.snapshots.store'));
        $this->assertTrue($router->has('vasaccounting.reports.snapshots.show'));
        $this->assertTrue($router->has('vasaccounting.reports.cash_book'));
        $this->assertTrue($router->has('vasaccounting.reports.bank_book'));
        $this->assertTrue($router->has('vasaccounting.reports.bank_reconciliation'));
        $this->assertTrue($router->has('vasaccounting.reports.receivables'));
        $this->assertTrue($router->has('vasaccounting.reports.payables'));
        $this->assertTrue($router->has('vasaccounting.reports.invoice_register'));
        $this->assertTrue($router->has('vasaccounting.reports.purchase_register'));
        $this->assertTrue($router->has('vasaccounting.reports.goods_receipt_register'));
        $this->assertTrue($router->has('vasaccounting.reports.procurement_discrepancies'));
        $this->assertTrue($router->has('vasaccounting.reports.procurement_discrepancy_ownership'));
        $this->assertTrue($router->has('vasaccounting.reports.procurement_discrepancy_ownership.assign_unassigned'));
        $this->assertTrue($router->has('vasaccounting.reports.procurement_discrepancy_ownership.assign_unassigned_to_me'));
        $this->assertTrue($router->has('vasaccounting.reports.procurement_aging'));
        $this->assertTrue($router->has('vasaccounting.reports.expense_outstanding'));
        $this->assertTrue($router->has('vasaccounting.reports.expense_register'));
        $this->assertTrue($router->has('vasaccounting.reports.expense_escalation_audit'));
        $this->assertTrue($router->has('vasaccounting.reports.expense_escalation_audit.retry_failed_dispatches'));
        $this->assertTrue($router->has('vasaccounting.reports.payroll_bridge'));
        $this->assertTrue($router->has('vasaccounting.reports.contracts'));
        $this->assertTrue($router->has('vasaccounting.reports.loans'));
        $this->assertTrue($router->has('vasaccounting.reports.costing'));
        $this->assertTrue($router->has('vasaccounting.reports.budget_variance'));
        $this->assertTrue($router->has('vasaccounting.reports.close_packet'));
        $this->assertTrue($router->has('vasaccounting.reports.operational_health'));
        $this->assertTrue($router->has('vasaccounting.api.health'));
        $this->assertTrue($router->has('vasaccounting.api.domains'));
        $this->assertTrue($router->has('vasaccounting.api.snapshots'));
        $this->assertTrue($router->has('vasaccounting.api.integration_runs'));
        $this->assertTrue($router->has('vasaccounting.api.posting.preview'));
        $this->assertTrue($router->has('vasaccounting.api.finance_documents.store'));
        $this->assertTrue($router->has('vasaccounting.api.finance_documents.submit'));
        $this->assertTrue($router->has('vasaccounting.api.finance_documents.approve'));
        $this->assertTrue($router->has('vasaccounting.api.finance_documents.match'));
        $this->assertTrue($router->has('vasaccounting.api.finance_documents.fulfill'));
        $this->assertTrue($router->has('vasaccounting.api.finance_documents.close'));
        $this->assertTrue($router->has('vasaccounting.api.finance_documents.post'));
        $this->assertTrue($router->has('vasaccounting.api.finance_documents.reverse'));
        $this->assertTrue($router->has('vasaccounting.api.finance_documents.trace'));
        $this->assertTrue($router->has('vasaccounting.api.treasury.statement_lines.candidates'));
        $this->assertTrue($router->has('vasaccounting.api.treasury.statement_lines.reconcile'));
        $this->assertTrue($router->has('vasaccounting.api.treasury.reconciliations.reverse'));
        $this->assertTrue($router->has('vasaccounting.api.treasury.exceptions.index'));
        $this->assertTrue($router->has('vasaccounting.api.treasury.statement_lines.refresh_exception'));
        $this->assertTrue($router->has('vasaccounting.api.webhooks.store'));
    }

    public function test_setup_and_report_routes_use_expected_uris(): void
    {
        $routes = app('router')->getRoutes();

        $this->assertSame(
            'vas-accounting/setup',
            $routes->getByName('vasaccounting.setup.index')->uri()
        );
        $this->assertSame(
            'vas-accounting/ui/dashboard/kpis',
            $routes->getByName('vasaccounting.ui.dashboard.kpis')->uri()
        );
        $this->assertSame(
            'vas-accounting/ui/dashboard/trends',
            $routes->getByName('vasaccounting.ui.dashboard.trends')->uri()
        );
        $this->assertSame(
            'vas-accounting/ui/dashboard/failures',
            $routes->getByName('vasaccounting.ui.dashboard.failures')->uri()
        );
        $this->assertSame(
            'vas-accounting/ui/reports/{reportKey}/datatable',
            $routes->getByName('vasaccounting.ui.reports.datatable')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/financial-statements',
            $routes->getByName('vasaccounting.reports.financial_statements')->uri()
        );
        $this->assertSame(
            'vas-accounting/cash-bank',
            $routes->getByName('vasaccounting.cash_bank.index')->uri()
        );
        $this->assertSame(
            'vas-accounting/cash-bank/treasury-documents',
            $routes->getByName('vasaccounting.cash_bank.treasury_documents.store')->uri()
        );
        $this->assertSame(
            'vas-accounting/cash-bank/treasury-documents/{document}/submit',
            $routes->getByName('vasaccounting.cash_bank.treasury_documents.submit')->uri()
        );
        $this->assertSame(
            'vas-accounting/cash-bank/treasury-documents/{document}/approve',
            $routes->getByName('vasaccounting.cash_bank.treasury_documents.approve')->uri()
        );
        $this->assertSame(
            'vas-accounting/cash-bank/treasury-documents/{document}/post',
            $routes->getByName('vasaccounting.cash_bank.treasury_documents.post')->uri()
        );
        $this->assertSame(
            'vas-accounting/cash-bank/treasury-documents/{document}/reverse',
            $routes->getByName('vasaccounting.cash_bank.treasury_documents.reverse')->uri()
        );
        $this->assertSame(
            'vas-accounting/cash-bank/statements/lines/{line}/canonical-reconcile',
            $routes->getByName('vasaccounting.cash_bank.statements.canonical_reconcile')->uri()
        );
        $this->assertSame(
            'vas-accounting/cash-bank/statements/lines/{line}/refresh-exception',
            $routes->getByName('vasaccounting.cash_bank.statements.refresh_exception')->uri()
        );
        $this->assertSame(
            'vas-accounting/cash-bank/statements/lines/{line}/ignore-exception',
            $routes->getByName('vasaccounting.cash_bank.statements.ignore_exception')->uri()
        );
        $this->assertSame(
            'vas-accounting/cash-bank/reconciliations/{reconciliation}/reverse',
            $routes->getByName('vasaccounting.cash_bank.reconciliations.reverse')->uri()
        );
        $this->assertSame(
            'vas-accounting/payment-documents',
            $routes->getByName('vasaccounting.payment_documents.index')->uri()
        );
        $this->assertSame(
            'vas-accounting/payment-documents/{voucher}/post',
            $routes->getByName('vasaccounting.payment_documents.post')->uri()
        );
        $this->assertSame(
            'vas-accounting/expenses',
            $routes->getByName('vasaccounting.expenses.index')->uri()
        );
        $this->assertSame(
            'vas-accounting/procurement',
            $routes->getByName('vasaccounting.procurement.index')->uri()
        );
        $this->assertSame(
            'vas-accounting/procurement/{document}/match',
            $routes->getByName('vasaccounting.procurement.match')->uri()
        );
        $this->assertSame(
            'vas-accounting/procurement/discrepancies/{exception}/take-ownership',
            $routes->getByName('vasaccounting.procurement.discrepancies.take_ownership')->uri()
        );
        $this->assertSame(
            'vas-accounting/procurement/discrepancies/{exception}/assign',
            $routes->getByName('vasaccounting.procurement.discrepancies.assign')->uri()
        );
        $this->assertSame(
            'vas-accounting/procurement/discrepancies/{exception}/resolve',
            $routes->getByName('vasaccounting.procurement.discrepancies.resolve')->uri()
        );
        $this->assertSame(
            'vas-accounting/procurement/{document}/fulfill',
            $routes->getByName('vasaccounting.procurement.fulfill')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/procurement-discrepancies',
            $routes->getByName('vasaccounting.reports.procurement_discrepancies')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/procurement-discrepancy-ownership',
            $routes->getByName('vasaccounting.reports.procurement_discrepancy_ownership')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/procurement-discrepancy-ownership/assign-unassigned',
            $routes->getByName('vasaccounting.reports.procurement_discrepancy_ownership.assign_unassigned')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/procurement-discrepancy-ownership/assign-unassigned-to-me',
            $routes->getByName('vasaccounting.reports.procurement_discrepancy_ownership.assign_unassigned_to_me')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/procurement-aging',
            $routes->getByName('vasaccounting.reports.procurement_aging')->uri()
        );
        $this->assertSame(
            'vas-accounting/expenses/{document}/post',
            $routes->getByName('vasaccounting.expenses.post')->uri()
        );
        $this->assertSame(
            'vas-accounting/expenses/{document}/reject',
            $routes->getByName('vasaccounting.expenses.reject')->uri()
        );
        $this->assertSame(
            'vas-accounting/expenses/{document}/escalate',
            $routes->getByName('vasaccounting.expenses.escalate')->uri()
        );
        $this->assertSame(
            'vas-accounting/expenses/{document}/retry-escalation-dispatch',
            $routes->getByName('vasaccounting.expenses.retry_escalation_dispatch')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/bank-reconciliation',
            $routes->getByName('vasaccounting.reports.bank_reconciliation')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/expense-outstanding',
            $routes->getByName('vasaccounting.reports.expense_outstanding')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/purchase-register',
            $routes->getByName('vasaccounting.reports.purchase_register')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/goods-receipt-register',
            $routes->getByName('vasaccounting.reports.goods_receipt_register')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/expense-register',
            $routes->getByName('vasaccounting.reports.expense_register')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/expense-escalation-audit',
            $routes->getByName('vasaccounting.reports.expense_escalation_audit')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/expense-escalation-audit/retry-failed-dispatches',
            $routes->getByName('vasaccounting.reports.expense_escalation_audit.retry_failed_dispatches')->uri()
        );
        $this->assertSame(
            'vas-accounting/invoices/{voucher}/approve',
            $routes->getByName('vasaccounting.invoices.approve')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/posting/preview',
            $routes->getByName('vasaccounting.api.posting.preview')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/finance-documents/{family}',
            $routes->getByName('vasaccounting.api.finance_documents.store')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/finance-documents/{document}/post',
            $routes->getByName('vasaccounting.api.finance_documents.post')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/finance-documents/{document}/trace',
            $routes->getByName('vasaccounting.api.finance_documents.trace')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/treasury/statement-lines/{statementLine}/candidates',
            $routes->getByName('vasaccounting.api.treasury.statement_lines.candidates')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/treasury/statement-lines/{statementLine}/reconcile',
            $routes->getByName('vasaccounting.api.treasury.statement_lines.reconcile')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/treasury/reconciliations/{reconciliation}/reverse',
            $routes->getByName('vasaccounting.api.treasury.reconciliations.reverse')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/treasury/exceptions',
            $routes->getByName('vasaccounting.api.treasury.exceptions.index')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/treasury/statement-lines/{statementLine}/refresh-exception',
            $routes->getByName('vasaccounting.api.treasury.statement_lines.refresh_exception')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/domains',
            $routes->getByName('vasaccounting.api.domains')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/finance-documents/{document}/approve',
            $routes->getByName('vasaccounting.api.finance_documents.approve')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/finance-documents/{document}/match',
            $routes->getByName('vasaccounting.api.finance_documents.match')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/finance-documents/{document}/fulfill',
            $routes->getByName('vasaccounting.api.finance_documents.fulfill')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/finance-documents/{document}/close',
            $routes->getByName('vasaccounting.api.finance_documents.close')->uri()
        );
        $this->assertSame(
            'vas-accounting/payroll/bridge',
            $routes->getByName('vasaccounting.payroll.bridge')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/budget-variance',
            $routes->getByName('vasaccounting.reports.budget_variance')->uri()
        );
        $this->assertSame(
            'vas-accounting/integrations/runs',
            $routes->getByName('vasaccounting.integrations.runs.store')->uri()
        );
        $this->assertSame(
            'vas-accounting/closing/period/{period}/soft-lock',
            $routes->getByName('vasaccounting.closing.soft_lock')->uri()
        );
        $this->assertSame(
            'vas-accounting/closing/period/{period}/procurement-discrepancies/assign-unassigned',
            $routes->getByName('vasaccounting.closing.procurement_discrepancies.assign_unassigned')->uri()
        );
        $this->assertSame(
            'vas-accounting/closing/period/{period}/procurement-discrepancies/assign-unassigned-to-me',
            $routes->getByName('vasaccounting.closing.procurement_discrepancies.assign_unassigned_to_me')->uri()
        );
        $this->assertSame(
            'vas-accounting/closing/period/{period}/procurement-discrepancies/{exception}/assign',
            $routes->getByName('vasaccounting.closing.procurement_discrepancies.assign')->uri()
        );
        $this->assertSame(
            'vas-accounting/cutover',
            $routes->getByName('vasaccounting.cutover.index')->uri()
        );
        $this->assertSame(
            'vas-accounting/cutover/settings',
            $routes->getByName('vasaccounting.cutover.settings.update')->uri()
        );
        $this->assertSame(
            'vas-accounting/inventory/documents/{document}/post',
            $routes->getByName('vasaccounting.inventory.documents.post')->uri()
        );
        $this->assertSame(
            'vas-accounting/reports/operational-health',
            $routes->getByName('vasaccounting.reports.operational_health')->uri()
        );
        $this->assertSame(
            'api/vas-accounting/webhooks/{provider}',
            $routes->getByName('vasaccounting.api.webhooks.store')->uri()
        );
    }

    public function test_legacy_account_routes_are_guarded_by_cutover_middleware(): void
    {
        $routes = app('router')->getRoutes();

        $this->assertContains(
            RedirectLegacyAccountingToVas::class,
            $routes->getByName('account.index')->gatherMiddleware()
        );
        $this->assertContains(
            RedirectLegacyAccountingToVas::class,
            $routes->getByName('payment-account.index')->gatherMiddleware()
        );
        $this->assertContains(
            RedirectLegacyAccountingToVas::class,
            $routes->getByName('account-types.index')->gatherMiddleware()
        );
    }
}
