<?php

use Modules\VasAccounting\Services\Adapters\ExpenseDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\EssentialsPayrollBridgeAdapter;
use Modules\VasAccounting\Services\Adapters\LocalTaxExportAdapter;
use Modules\VasAccounting\Services\Adapters\InventoryDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\NullBankStatementImportAdapter;
use Modules\VasAccounting\Services\Adapters\OpeningStockDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\PaymentDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\PurchaseDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\PurchaseReturnDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\SellDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\SellReturnDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\StockAdjustmentDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\StockTransferDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\SandboxEInvoiceAdapter;
use Modules\VasAccounting\Services\Adapters\VnptEInvoiceAdapter;
use Modules\VasAccounting\Services\Adapters\VnptTaxExportAdapter;

return [
    'version' => '1.1.0',
    'business_module_key' => 'vas_accounting',
    'book_currency' => 'VND',
    'inventory_method' => 'weighted_average',
    'default_timezone' => 'Asia/Ho_Chi_Minh',
    'api_guard' => 'auth:api',
    'report_route_prefix' => 'vas-accounting/reports',
    'compliance_profiles' => [
        'default' => 'tt99_2025',
        'profiles' => [
            'tt99_2025' => [
                'label' => 'Circular 99/2025/TT-BTC',
                'effective_date' => '2026-01-01',
                'legacy_bridge_allowed' => true,
                'required_posting_map_keys' => [
                    'cash',
                    'bank',
                    'accounts_receivable',
                    'accounts_payable',
                    'revenue',
                    'vat_output',
                    'vat_input',
                    'inventory',
                    'cogs',
                    'expense',
                    'fixed_asset',
                    'accumulated_depreciation',
                    'depreciation_expense',
                    'stock_adjustment',
                    'stock_transfer',
                ],
                'required_reports' => [
                    'trial_balance',
                    'general_ledger',
                    'financial_statements',
                    'vat',
                    'close_packet',
                ],
                'required_statement_types' => [
                    'balance_sheet',
                    'income_statement',
                    'cash_flow',
                    'notes',
                ],
                'filing_requirements' => [
                    'einvoice_provider' => 'vnpt',
                    'tax_export_provider' => 'vnpt',
                ],
            ],
            'tt200_legacy_bridge' => [
                'label' => 'TT200 Legacy Bridge',
                'effective_date' => '2015-01-01',
                'legacy_bridge_allowed' => true,
                'required_posting_map_keys' => [
                    'cash',
                    'bank',
                    'accounts_receivable',
                    'accounts_payable',
                    'revenue',
                    'vat_output',
                    'vat_input',
                    'inventory',
                    'cogs',
                    'expense',
                ],
                'required_reports' => [
                    'trial_balance',
                    'general_ledger',
                    'financial_statements',
                ],
                'required_statement_types' => [
                    'balance_sheet',
                    'income_statement',
                    'cash_flow',
                ],
                'filing_requirements' => [
                    'einvoice_provider' => null,
                    'tax_export_provider' => null,
                ],
            ],
        ],
    ],
    'document_statuses' => [
        'draft' => 'Draft',
        'pending_approval' => 'Pending approval',
        'approved' => 'Approved',
        'posted' => 'Posted',
        'reversed' => 'Reversed',
        'cancelled' => 'Cancelled',
    ],
    'period_statuses' => [
        'open' => 'Open',
        'soft_locked' => 'Soft locked',
        'closed' => 'Closed',
    ],
    'feature_flags' => [
        'cash_bank' => true,
        'receivables' => true,
        'payables' => true,
        'invoices' => true,
        'inventory' => true,
        'tools' => true,
        'assets' => true,
        'tax' => true,
        'einvoices' => true,
        'payroll' => true,
        'contracts' => true,
        'loans' => true,
        'costing' => true,
        'budgets' => true,
        'integrations' => true,
        'reports' => true,
        'closing' => true,
        'finance_core_v2' => true,
        'workflow_v2' => true,
        'posting_engine_v2' => true,
        'traceability_v2' => true,
        'p2p_v2' => true,
        'o2c_v2' => false,
        'inventory_v2' => false,
        'treasury_v2' => false,
        'expense_v2' => true,
        'assets_v2' => false,
        'payroll_v2' => false,
        'tax_v2' => false,
        'close_v2' => false,
    ],
    'finance_core_defaults' => [
        'default_event_type' => 'post',
        'supported_account_sources' => ['fixed', 'document_line_account', 'document_line_debit', 'document_line_credit', 'document_line_tax'],
        'supported_amount_sources' => ['line_amount', 'tax_amount', 'gross_amount', 'unit_price'],
        'supported_workflow_statuses' => ['draft', 'submitted', 'approved', 'matched', 'converted_to_po', 'ordered', 'released', 'partially_received', 'fully_received', 'partially_delivered', 'fully_delivered', 'posted', 'partially_collected', 'collected', 'closed', 'reversed', 'cancelled'],
        'supported_accounting_statuses' => ['not_ready', 'pending_approval', 'ready_to_post', 'matched', 'posted', 'closed', 'reversed', 'cancelled'],
    ],
    'finance_document_blueprints' => [
        'procurement' => [
            'purchase_requisition' => [
                'posting_mode' => 'none',
                'required_counterparty' => false,
                'allowed_parent_types' => [],
                'allowed_child_types' => ['purchase_order'],
                'postable_workflow_statuses' => [],
            ],
            'purchase_order' => [
                'posting_mode' => 'none',
                'required_counterparty' => true,
                'allowed_parent_types' => ['purchase_requisition'],
                'allowed_child_types' => ['goods_receipt', 'supplier_invoice'],
                'postable_workflow_statuses' => [],
            ],
            'goods_receipt' => [
                'posting_mode' => 'manual',
                'required_counterparty' => true,
                'allowed_parent_types' => ['purchase_order'],
                'allowed_child_types' => ['supplier_invoice'],
                'postable_workflow_statuses' => ['approved'],
            ],
        ],
        'payables' => [
            'supplier_invoice' => [
                'posting_mode' => 'manual',
                'required_counterparty' => true,
                'allowed_parent_types' => ['goods_receipt', 'purchase_order'],
                'allowed_child_types' => ['supplier_payment'],
                'postable_workflow_statuses' => ['approved', 'matched'],
            ],
        ],
        'cash_bank' => [
            'supplier_payment' => [
                'posting_mode' => 'manual',
                'required_counterparty' => true,
                'allowed_parent_types' => ['supplier_invoice'],
                'allowed_child_types' => [],
                'postable_workflow_statuses' => ['approved'],
            ],
            'customer_receipt' => [
                'posting_mode' => 'manual',
                'required_counterparty' => true,
                'allowed_parent_types' => ['customer_invoice'],
                'allowed_child_types' => [],
                'postable_workflow_statuses' => ['approved'],
            ],
            'cash_transfer' => [
                'posting_mode' => 'manual',
                'required_counterparty' => false,
                'allowed_parent_types' => [],
                'allowed_child_types' => [],
                'postable_workflow_statuses' => ['approved'],
            ],
            'bank_transfer' => [
                'posting_mode' => 'manual',
                'required_counterparty' => false,
                'allowed_parent_types' => [],
                'allowed_child_types' => [],
                'postable_workflow_statuses' => ['approved'],
            ],
            'petty_cash_expense' => [
                'posting_mode' => 'manual',
                'required_counterparty' => false,
                'allowed_parent_types' => [],
                'allowed_child_types' => [],
                'postable_workflow_statuses' => ['approved'],
            ],
        ],
        'expense_management' => [
            'expense_claim' => [
                'posting_mode' => 'manual',
                'required_counterparty' => false,
                'allowed_parent_types' => ['advance_request'],
                'allowed_child_types' => ['reimbursement_voucher', 'advance_settlement'],
                'postable_workflow_statuses' => ['approved'],
            ],
            'advance_request' => [
                'posting_mode' => 'manual',
                'required_counterparty' => false,
                'allowed_parent_types' => [],
                'allowed_child_types' => ['expense_claim', 'advance_settlement'],
                'postable_workflow_statuses' => ['approved'],
            ],
            'advance_settlement' => [
                'posting_mode' => 'manual',
                'required_counterparty' => false,
                'allowed_parent_types' => ['advance_request', 'expense_claim'],
                'allowed_child_types' => [],
                'postable_workflow_statuses' => ['approved'],
            ],
            'reimbursement_voucher' => [
                'posting_mode' => 'manual',
                'required_counterparty' => false,
                'allowed_parent_types' => ['expense_claim'],
                'allowed_child_types' => [],
                'postable_workflow_statuses' => ['approved'],
            ],
        ],
        'sales' => [
            'quotation' => [
                'posting_mode' => 'none',
                'required_counterparty' => true,
                'allowed_parent_types' => [],
                'allowed_child_types' => ['sales_order'],
                'postable_workflow_statuses' => [],
            ],
            'sales_order' => [
                'posting_mode' => 'none',
                'required_counterparty' => true,
                'allowed_parent_types' => ['quotation'],
                'allowed_child_types' => ['delivery', 'customer_invoice'],
                'postable_workflow_statuses' => [],
            ],
            'delivery' => [
                'posting_mode' => 'manual',
                'required_counterparty' => true,
                'allowed_parent_types' => ['sales_order'],
                'allowed_child_types' => ['customer_invoice'],
                'postable_workflow_statuses' => ['approved'],
            ],
        ],
        'receivables' => [
            'customer_invoice' => [
                'posting_mode' => 'manual',
                'required_counterparty' => true,
                'allowed_parent_types' => ['delivery', 'sales_order'],
                'allowed_child_types' => ['customer_receipt'],
                'postable_workflow_statuses' => ['approved'],
            ],
        ],
    ],
    'finance_document_transition_events' => [
        'purchase_requisition' => [
            'fulfill' => [
                'allowed_from' => ['approved'],
                'targets' => [
                    'converted_to_po' => ['workflow_status' => 'converted_to_po', 'accounting_status' => 'not_ready'],
                ],
            ],
            'close' => [
                'allowed_from' => ['approved', 'converted_to_po'],
                'workflow_status' => 'closed',
                'accounting_status' => 'closed',
            ],
        ],
        'purchase_order' => [
            'fulfill' => [
                'allowed_from' => ['approved', 'ordered', 'partially_received'],
                'targets' => [
                    'ordered' => ['workflow_status' => 'ordered', 'accounting_status' => 'not_ready'],
                    'partially_received' => ['workflow_status' => 'partially_received', 'accounting_status' => 'not_ready'],
                    'fully_received' => ['workflow_status' => 'fully_received', 'accounting_status' => 'not_ready'],
                ],
            ],
            'close' => [
                'allowed_from' => ['approved', 'ordered', 'partially_received', 'fully_received'],
                'workflow_status' => 'closed',
                'accounting_status' => 'closed',
            ],
        ],
        'supplier_invoice' => [
            'match' => [
                'allowed_from' => ['approved'],
                'workflow_status' => 'matched',
                'accounting_status' => 'ready_to_post',
            ],
            'close' => [
                'allowed_from' => ['posted'],
                'workflow_status' => 'closed',
                'accounting_status' => 'closed',
            ],
        ],
        'quotation' => [
            'close' => [
                'allowed_from' => ['approved'],
                'workflow_status' => 'closed',
                'accounting_status' => 'closed',
            ],
        ],
        'sales_order' => [
            'fulfill' => [
                'allowed_from' => ['approved', 'released', 'partially_delivered'],
                'targets' => [
                    'released' => ['workflow_status' => 'released', 'accounting_status' => 'not_ready'],
                    'partially_delivered' => ['workflow_status' => 'partially_delivered', 'accounting_status' => 'not_ready'],
                    'fully_delivered' => ['workflow_status' => 'fully_delivered', 'accounting_status' => 'not_ready'],
                ],
            ],
            'close' => [
                'allowed_from' => ['approved', 'released', 'partially_delivered', 'fully_delivered'],
                'workflow_status' => 'closed',
                'accounting_status' => 'closed',
            ],
        ],
        'customer_invoice' => [
            'close' => [
                'allowed_from' => ['posted'],
                'workflow_status' => 'closed',
                'accounting_status' => 'closed',
            ],
        ],
        'expense_claim' => [
            'close' => [
                'allowed_from' => ['posted'],
                'workflow_status' => 'closed',
                'accounting_status' => 'closed',
            ],
        ],
        'advance_request' => [
            'close' => [
                'allowed_from' => ['posted'],
                'workflow_status' => 'closed',
                'accounting_status' => 'closed',
            ],
        ],
        'advance_settlement' => [
            'close' => [
                'allowed_from' => ['posted'],
                'workflow_status' => 'closed',
                'accounting_status' => 'closed',
            ],
        ],
        'reimbursement_voucher' => [
            'close' => [
                'allowed_from' => ['posted'],
                'workflow_status' => 'closed',
                'accounting_status' => 'closed',
            ],
        ],
    ],
    'finance_matching' => [
        'supplier_invoice' => [
            'require_parent_link' => true,
            'allow_purchase_order_only' => true,
            'quantity_variance_tolerance' => '0.0001',
            'amount_variance_tolerance' => '0.0100',
            'tax_variance_tolerance' => '0.0100',
        ],
    ],
    'inventory_ledger_defaults' => [
        'costing_method' => 'weighted_average',
        'allow_negative_stock' => false,
    ],
    'treasury_reconciliation' => [
        'default_candidate_limit' => 5,
        'candidate_date_window_days' => 7,
        'amount_tolerance' => '0.0100',
        'candidate_amount_variance' => '1000.0000',
        'suggest_threshold' => 70,
    ],
    'cutover_defaults' => [
        'legacy_routes_mode' => 'observe',
        'hide_legacy_accounting_menu' => false,
        'parallel_run_status' => 'not_started',
        'parallel_run_notes' => null,
        'uat_statuses' => [],
        'last_parity_check_at' => null,
        'last_legacy_redirect_at' => null,
        'family_modes' => [
            'payments' => 'legacy',
            'purchase_ap' => 'legacy',
            'sales_ar' => 'legacy',
            'payroll' => 'bridge',
        ],
    ],
    'rollout_defaults' => [
        'status' => 'pilot',
        'target_go_live_date' => null,
        'support_owner' => null,
        'training_notes' => null,
        'enabled_branch_ids' => [],
        'enabled_document_families' => [],
        'rollout_notes' => null,
    ],
    'approval_defaults' => [
        'default_manual_voucher_status' => 'draft',
        'require_manual_voucher_approval' => false,
        'finance_document_defaults' => [
            'maker_checker' => true,
            'auto_approve_without_steps' => false,
            'default_policy_code' => 'FINANCE_DOCUMENT_DEFAULT',
            'default_step_role' => 'finance_manager',
            'default_permission_code' => 'vasaccounting.finance_documents.approve',
        ],
        'expense_document_policies' => [
            'expense_claim' => [
                'maker_checker' => true,
                'tiers' => [
                    [
                        'max_amount' => 5000000,
                        'policy_code' => 'EXPENSE_CLAIM_STANDARD',
                        'steps' => [
                            [
                                'approver_role' => 'branch_manager',
                                'permission_code' => 'vas_accounting.expenses.manage',
                                'label' => 'Branch expense review',
                                'sla_hours' => 24,
                                'warning_hours' => 4,
                                'escalation_role' => 'finance_manager',
                            ],
                        ],
                    ],
                    [
                        'min_amount' => 5000000.0001,
                        'policy_code' => 'EXPENSE_CLAIM_HIGH_VALUE',
                        'steps' => [
                            [
                                'approver_role' => 'branch_manager',
                                'permission_code' => 'vas_accounting.expenses.manage',
                                'label' => 'Branch expense review',
                                'sla_hours' => 12,
                                'warning_hours' => 3,
                                'escalation_role' => 'finance_manager',
                            ],
                            [
                                'approver_role' => 'finance_manager',
                                'permission_code' => 'vas_accounting.expenses.manage',
                                'label' => 'Finance approval',
                                'sla_hours' => 12,
                                'warning_hours' => 2,
                            ],
                        ],
                    ],
                ],
            ],
            'advance_request' => [
                'maker_checker' => true,
                'tiers' => [
                    [
                        'max_amount' => 10000000,
                        'policy_code' => 'ADVANCE_REQUEST_STANDARD',
                        'steps' => [
                            [
                                'approver_role' => 'branch_manager',
                                'permission_code' => 'vas_accounting.expenses.manage',
                                'label' => 'Branch cash advance review',
                                'sla_hours' => 8,
                                'warning_hours' => 2,
                                'escalation_role' => 'finance_manager',
                            ],
                        ],
                    ],
                    [
                        'min_amount' => 10000000.0001,
                        'policy_code' => 'ADVANCE_REQUEST_HIGH_VALUE',
                        'steps' => [
                            [
                                'approver_role' => 'branch_manager',
                                'permission_code' => 'vas_accounting.expenses.manage',
                                'label' => 'Branch cash advance review',
                                'sla_hours' => 8,
                                'warning_hours' => 2,
                                'escalation_role' => 'finance_manager',
                            ],
                            [
                                'approver_role' => 'finance_manager',
                                'permission_code' => 'vas_accounting.expenses.manage',
                                'label' => 'Finance cash control review',
                                'sla_hours' => 12,
                                'warning_hours' => 3,
                            ],
                        ],
                    ],
                ],
            ],
            'advance_settlement' => [
                'maker_checker' => true,
                'tiers' => [
                    [
                        'policy_code' => 'ADVANCE_SETTLEMENT_STANDARD',
                        'steps' => [
                            [
                                'approver_role' => 'finance_manager',
                                'permission_code' => 'vas_accounting.expenses.manage',
                                'label' => 'Settlement validation',
                                'sla_hours' => 8,
                                'warning_hours' => 2,
                            ],
                        ],
                    ],
                ],
            ],
            'reimbursement_voucher' => [
                'maker_checker' => true,
                'tiers' => [
                    [
                        'max_amount' => 5000000,
                        'policy_code' => 'REIMBURSEMENT_STANDARD',
                        'steps' => [
                            [
                                'approver_role' => 'finance_manager',
                                'permission_code' => 'vas_accounting.expenses.manage',
                                'label' => 'Finance reimbursement review',
                                'sla_hours' => 8,
                                'warning_hours' => 2,
                            ],
                        ],
                    ],
                    [
                        'min_amount' => 5000000.0001,
                        'policy_code' => 'REIMBURSEMENT_HIGH_VALUE',
                        'steps' => [
                            [
                                'approver_role' => 'branch_manager',
                                'permission_code' => 'vas_accounting.expenses.manage',
                                'label' => 'Branch reimbursement review',
                                'sla_hours' => 8,
                                'warning_hours' => 2,
                                'escalation_role' => 'finance_manager',
                            ],
                            [
                                'approver_role' => 'finance_manager',
                                'permission_code' => 'vas_accounting.expenses.manage',
                                'label' => 'Finance reimbursement review',
                                'sla_hours' => 12,
                                'warning_hours' => 3,
                            ],
                        ],
                    ],
                ],
            ],
        ],
        'native_document_defaults' => [
            'invoice' => [
                'default_status' => 'draft',
                'requires_approval' => true,
                'requires_rule' => true,
            ],
            'payment' => [
                'default_status' => 'draft',
                'requires_approval' => true,
                'requires_rule' => true,
            ],
            'payroll' => [
                'default_status' => 'draft',
                'requires_approval' => true,
                'requires_rule' => true,
            ],
            'manual' => [
                'default_status' => 'draft',
                'requires_approval' => false,
                'requires_rule' => false,
            ],
        ],
    ],
    'family_mode_options' => [
        'legacy' => 'Legacy owned',
        'pilot' => 'Pilot in VAS',
        'native' => 'VAS owned',
        'bridge' => 'Bridge mode',
    ],
    'cutover_uat_personas' => [
        'accountant' => [
            'label' => 'Accountant',
            'description' => 'Validate trial balance, financial statements, close packet generation, and reversal controls.',
            'focus_area' => 'Core ledger and statutory reports',
        ],
        'cashier' => [
            'label' => 'Cashier',
            'description' => 'Validate cashbooks, bank accounts, statement import, reconciliation actions, and payment flows.',
            'focus_area' => 'Cash, cashier, and bank operations',
        ],
        'ap_ar_clerk' => [
            'label' => 'AP/AR clerk',
            'description' => 'Validate invoice register, allocations, aging reports, and collection or payment readiness.',
            'focus_area' => 'Receivables, payables, and invoice settlement',
        ],
        'warehouse_accountant' => [
            'label' => 'Warehouse accountant',
            'description' => 'Validate warehouse masters, valuation views, and inventory report reproducibility by branch.',
            'focus_area' => 'Warehouse and inventory accounting',
        ],
        'tax_accountant' => [
            'label' => 'Tax accountant',
            'description' => 'Validate VAT books, tax export payloads, and e-invoice traceability.',
            'focus_area' => 'Tax center and e-invoice readiness',
        ],
        'payroll_accountant' => [
            'label' => 'Payroll accountant',
            'description' => 'Validate payroll bridge accruals, payroll payment bridge, and downstream reporting.',
            'focus_area' => 'Payroll bridge and finance postings',
        ],
        'finance_manager' => [
            'label' => 'Finance manager',
            'description' => 'Validate close controls, report snapshots, integration operations, and cutover readiness.',
            'focus_area' => 'Governance, close, and rollout oversight',
        ],
        'branch_manager' => [
            'label' => 'Branch manager',
            'description' => 'Validate branch filtering, enabled rollout branches, and branch-level cash and document coverage.',
            'focus_area' => 'Branch rollout and operational sign-off',
        ],
    ],
    'legacy_accounting_route_map' => [
        'account' => [
            'legacy_label' => 'Legacy account register and transaction maintenance',
            'legacy_paths' => ['account/account', 'account/account/*', 'account/fund-transfer/*', 'account/deposit/*', 'account/close/*', 'account/activate/*', 'account/delete-account-transaction/*', 'account/edit-account-transaction/*', 'account/update-account-transaction/*', 'account/get-account-balance/*'],
            'route' => 'vasaccounting.cash_bank.index',
            'target_label' => 'VAS Cash & Bank',
        ],
        'balance-sheet' => [
            'legacy_label' => 'Legacy balance sheet report',
            'legacy_paths' => ['account/balance-sheet'],
            'route' => 'vasaccounting.reports.financial_statements',
            'target_label' => 'VAS Financial Statements',
            'query' => ['statement' => 'balance_sheet'],
        ],
        'trial-balance' => [
            'legacy_label' => 'Legacy trial balance report',
            'legacy_paths' => ['account/trial-balance'],
            'route' => 'vasaccounting.reports.trial_balance',
            'target_label' => 'VAS Trial Balance',
        ],
        'payment-account-report' => [
            'legacy_label' => 'Legacy payment account report',
            'legacy_paths' => ['account/payment-account-report'],
            'route' => 'vasaccounting.reports.bank_book',
            'target_label' => 'VAS Bank Book',
        ],
        'payment-account' => [
            'legacy_label' => 'Legacy payment account maintenance',
            'legacy_paths' => ['payment-account', 'payment-account/*'],
            'route' => 'vasaccounting.cash_bank.index',
            'target_label' => 'VAS Cash & Bank',
        ],
        'link-account' => [
            'legacy_label' => 'Legacy account-linking workflow',
            'legacy_paths' => ['account/link-account/*'],
            'route' => 'vasaccounting.cash_bank.index',
            'target_label' => 'VAS Cash & Bank',
        ],
        'cash-flow' => [
            'legacy_label' => 'Legacy cash flow report',
            'legacy_paths' => ['account/cash-flow'],
            'route' => 'vasaccounting.reports.financial_statements',
            'target_label' => 'VAS Financial Statements',
            'query' => ['statement' => 'cash_flow'],
        ],
        'account-types' => [
            'legacy_label' => 'Legacy account type maintenance',
            'legacy_paths' => ['account-types', 'account-types/*'],
            'route' => 'vasaccounting.chart.index',
            'target_label' => 'VAS Chart of Accounts',
        ],
    ],
    'document_family_by_source' => [
        'manual' => 'manual',
        'legacy_opening_balance' => 'manual',
        'legacy_account_transaction' => 'payment',
        'transaction_payment' => 'payment',
        'sell' => 'invoice',
        'sell_return' => 'invoice',
        'purchase' => 'invoice',
        'purchase_return' => 'invoice',
        'expense' => 'invoice',
        'stock_adjustment' => 'inventory',
        'stock_transfer' => 'inventory',
        'opening_stock' => 'inventory',
        'inventory_document' => 'inventory',
        'payroll' => 'payroll',
        'native_invoice' => 'invoice',
        'native_payment' => 'payment',
        'native_payroll' => 'payroll',
    ],
    'module_area_by_source' => [
        'manual' => 'accounting',
        'legacy_opening_balance' => 'accounting',
        'legacy_account_transaction' => 'cash_bank',
        'transaction_payment' => 'cash_bank',
        'sell' => 'invoices',
        'sell_return' => 'receivables',
        'purchase' => 'payables',
        'purchase_return' => 'payables',
        'expense' => 'payables',
        'stock_adjustment' => 'inventory',
        'stock_transfer' => 'inventory',
        'opening_stock' => 'inventory',
        'inventory_document' => 'inventory',
        'payroll' => 'payroll',
        'native_invoice' => 'invoices',
        'native_payment' => 'cash_bank',
        'native_payroll' => 'payroll',
    ],
    'native_document_families' => [
        'invoice' => [
            'source_type' => 'native_invoice',
            'module_area' => 'invoices',
            'route_prefix' => 'vas-accounting/invoices',
            'default_status' => 'draft',
            'cutover_mode_key' => 'sales_ar',
            'coexistence_mode' => 'parallel',
            'sales_guardrails' => [
                'block_inventory_impact' => true,
                'mode' => 'financial_only',
            ],
            'bridges' => [
                'quote_release' => [
                    'enabled' => false,
                    'strategy' => 'legacy_default',
                ],
                'subscription_release' => [
                    'enabled' => false,
                    'strategy' => 'legacy_default',
                ],
            ],
            'sequence_keys' => [
                'sales_invoice' => 'sales_invoice',
                'purchase_invoice' => 'purchase_invoice',
                'sales_credit_note' => 'sales_credit_note',
                'purchase_debit_note' => 'purchase_debit_note',
            ],
        ],
        'payment' => [
            'source_type' => 'native_payment',
            'module_area' => 'cash_bank',
            'route_prefix' => 'vas-accounting/payment-documents',
            'default_status' => 'draft',
            'cutover_mode_key' => 'payments',
            'coexistence_mode' => 'parallel',
            'sequence_keys' => [
                'cash_receipt' => 'cash_receipt',
                'cash_payment' => 'cash_payment',
                'bank_receipt' => 'bank_receipt',
                'bank_payment' => 'bank_payment',
            ],
        ],
        'payroll' => [
            'source_type' => 'native_payroll',
            'module_area' => 'payroll',
            'route_prefix' => 'vas-accounting/payroll',
            'default_status' => 'draft',
            'cutover_mode_key' => 'payroll',
            'coexistence_mode' => 'parallel',
            'sequence_keys' => [
                'payroll_accrual' => 'payroll_accrual',
                'payroll_payment' => 'payroll_payment',
            ],
        ],
    ],
    'enterprise_domains' => [
        'finance_core' => [
            'route' => 'vasaccounting.dashboard.index',
            'path' => 'finance-core',
            'permission' => 'vas_accounting.access',
            'title' => 'Finance Core & Posting',
            'nav_label' => 'Finance Core',
            'subtitle' => 'Canonical finance documents, configurable posting rules, traceability, and the enterprise posting engine foundation.',
            'record_table' => 'vas_fin_documents',
            'record_label' => 'Finance documents',
            'capabilities' => [
                ['title' => 'Canonical finance documents', 'description' => 'Operational finance documents are stored separately from legacy vouchers so migration can happen family by family.'],
                ['title' => 'Posting preview and rule versioning', 'description' => 'Posting previews resolve configurable rule sets and account derivation before anything is posted to the journal.'],
                ['title' => 'Document-to-journal traceability', 'description' => 'Every accounting event and journal line is linked back to the source document chain for audit and control evidence.'],
            ],
        ],
        'cash_bank' => [
            'route' => 'vasaccounting.cash_bank.index',
            'path' => 'cash-bank',
            'permission' => 'vas_accounting.cash_bank.manage',
            'title' => 'Cash, Cashier & Bank',
            'nav_label' => 'Cash & Bank',
            'subtitle' => 'Cashbooks, cashier sessions, bank accounts, deposits, fund transfers, and reconciliation queues.',
            'record_table' => 'vas_cashbooks',
            'record_label' => 'Cashbooks',
            'provider_config_key' => 'bank_statement_import_adapters',
            'capabilities' => [
                ['title' => 'Cashbooks & teller control', 'description' => 'Branch-aware cashbooks and cashier accountability for daily opening and close.'],
                ['title' => 'Bank reconciliation', 'description' => 'Statement import, match queues, and reconciliation exceptions connected to posted vouchers.'],
                ['title' => 'Fund movement lifecycle', 'description' => 'Receipts, payments, deposits, and transfers follow the same approval and posting path.'],
            ],
        ],
        'receivables' => [
            'route' => 'vasaccounting.receivables.index',
            'path' => 'receivables',
            'permission' => 'vas_accounting.receivables.manage',
            'title' => 'Receivables',
            'nav_label' => 'Receivables',
            'subtitle' => 'Customer subledger allocations, statements, aging, and collection workflows.',
            'record_table' => 'vas_receivable_allocations',
            'record_label' => 'AR allocations',
            'capabilities' => [
                ['title' => 'Settlement allocation', 'description' => 'Match receipts against invoices and keep residual balances visible by customer.'],
                ['title' => 'Customer statements', 'description' => 'Prepare customer statements and aging views from VAS-ledger allocations.'],
                ['title' => 'Credit control', 'description' => 'Surface overdue items and approval queues before period close.'],
            ],
        ],
        'payables' => [
            'route' => 'vasaccounting.payables.index',
            'path' => 'payables',
            'permission' => 'vas_accounting.payables.manage',
            'title' => 'Payables',
            'nav_label' => 'Payables',
            'subtitle' => 'Vendor bills, settlements, allocation tracking, and supplier aging.',
            'record_table' => 'vas_payable_allocations',
            'record_label' => 'AP allocations',
            'capabilities' => [
                ['title' => 'Bill settlement', 'description' => 'Allocate vendor payments across bills, returns, and expense settlements.'],
                ['title' => 'Vendor aging', 'description' => 'Surface current and overdue liabilities with branch-aware filters.'],
                ['title' => 'Payment readiness', 'description' => 'Keep payable balances tied to posted vouchers and approval status.'],
            ],
        ],
        'invoices' => [
            'route' => 'vasaccounting.invoices.index',
            'path' => 'invoices',
            'permission' => 'vas_accounting.invoices.manage',
            'title' => 'Sales & Purchase Invoices',
            'nav_label' => 'Invoices',
            'subtitle' => 'Sales invoices, purchase invoices, credit notes, debit notes, and document controls.',
            'record_table' => 'vas_vouchers',
            'record_label' => 'Invoice vouchers',
            'capabilities' => [
                ['title' => 'Invoice lifecycle', 'description' => 'Draft, approval, post, reversal, and cancellation all follow one document model.'],
                ['title' => 'Credit and debit notes', 'description' => 'Returns and adjustments stay linked to the original document chain.'],
                ['title' => 'Branch numbering', 'description' => 'Document numbering is ready for branch and period-aware expansion.'],
            ],
        ],
        'inventory' => [
            'route' => 'vasaccounting.inventory.index',
            'path' => 'inventory',
            'permission' => 'vas_accounting.inventory.manage',
            'title' => 'Warehouse & Inventory',
            'nav_label' => 'Inventory',
            'subtitle' => 'Warehouse accounting, valuation, movement traceability, and stock reconciliation.',
            'record_table' => 'vas_warehouses',
            'record_label' => 'Warehouses',
            'capabilities' => [
                ['title' => 'Warehouse masters', 'description' => 'Track warehouse structures alongside branch locations for inventory accounting.'],
                ['title' => 'Movement accounting', 'description' => 'Receipts, issues, adjustments, and transfers map cleanly into the ledger.'],
                ['title' => 'Close-ready valuation', 'description' => 'Inventory valuation remains reproducible by period and warehouse.'],
            ],
        ],
        'expenses' => [
            'route' => 'vasaccounting.expenses.index',
            'path' => 'expenses',
            'permission' => 'vas_accounting.expenses.manage',
            'title' => 'Expense Management',
            'nav_label' => 'Expenses',
            'subtitle' => 'Expense claims, employee advances, settlements, reimbursements, and dimension-aware cost capture.',
            'record_table' => 'vas_fin_documents',
            'document_family' => 'expense_management',
            'record_label' => 'Expense documents',
            'capabilities' => [
                ['title' => 'Native employee expense flows', 'description' => 'Expense claims and advances move through the same canonical finance document workflow as other operational documents.'],
                ['title' => 'Dimension-aware cost capture', 'description' => 'Department, cost center, project, and branch tagging are preserved on the finance document line for later reporting.'],
                ['title' => 'Posting-ready claims and reimbursements', 'description' => 'Claims, settlements, and reimbursements can post straight through the finance-core engine with tax and traceability.'],
            ],
        ],
        'tools' => [
            'route' => 'vasaccounting.tools.index',
            'path' => 'tools',
            'permission' => 'vas_accounting.tools.manage',
            'title' => 'Tools & Instruments',
            'nav_label' => 'Tools',
            'subtitle' => 'Tool registers, issue tracking, amortization schedules, and remaining value control.',
            'record_table' => 'vas_tools',
            'record_label' => 'Tools',
            'capabilities' => [
                ['title' => 'Register & issuance', 'description' => 'Track tools from acquisition through issue to departments, projects, or branches.'],
                ['title' => 'Amortization', 'description' => 'Prepare periodic expense recognition for tools and instruments.'],
                ['title' => 'Control dimensions', 'description' => 'Attach tool usage to department, cost center, and project dimensions.'],
            ],
        ],
        'assets' => [
            'route' => 'vasaccounting.assets.index',
            'path' => 'fixed-assets',
            'permission' => 'vas_accounting.assets.manage',
            'title' => 'Fixed Assets',
            'nav_label' => 'Assets',
            'subtitle' => 'Asset register, capitalization, depreciation, transfer, and disposal workflows.',
            'record_table' => 'vas_fixed_assets',
            'record_label' => 'Fixed assets',
            'capabilities' => [
                ['title' => 'Asset register', 'description' => 'Track acquisitions, useful life, depreciation, and disposal references.'],
                ['title' => 'Depreciation control', 'description' => 'Keep monthly depreciation tied to period close blockers and vouchers.'],
                ['title' => 'Lifecycle traceability', 'description' => 'Prepare transfer and disposal events without leaving the VAS ledger.'],
            ],
        ],
        'tax' => [
            'route' => 'vasaccounting.tax.index',
            'path' => 'tax',
            'permission' => 'vas_accounting.tax.manage',
            'title' => 'Tax Center',
            'nav_label' => 'Tax',
            'subtitle' => 'VAT books, declaration datasets, tax adjustments, and audit-ready tax logs.',
            'record_table' => 'vas_tax_codes',
            'record_label' => 'Tax codes',
            'provider_config_key' => 'tax_export_adapters',
            'capabilities' => [
                ['title' => 'Tax code controls', 'description' => 'Use VAS tax codes consistently across invoice and journal postings.'],
                ['title' => 'Declaration exports', 'description' => 'Keep tax export adapters ready for declaration packages and compliance data.'],
                ['title' => 'Adjustment traceability', 'description' => 'Tax corrections keep an approval and audit trail.'],
            ],
        ],
        'einvoices' => [
            'route' => 'vasaccounting.einvoices.index',
            'path' => 'e-invoices',
            'permission' => 'vas_accounting.einvoice.manage',
            'title' => 'E-Invoices',
            'nav_label' => 'E-Invoices',
            'subtitle' => 'Provider issue, sync, cancel, replace, and correction workflows for posted invoice documents.',
            'record_table' => 'vas_einvoice_documents',
            'record_label' => 'E-invoices',
            'provider_config_key' => 'einvoice_adapters',
            'capabilities' => [
                ['title' => 'Provider-ready adapters', 'description' => 'Adapters can be swapped without changing the voucher lifecycle.'],
                ['title' => 'Document logs', 'description' => 'Every issue and sync action keeps request and response history.'],
                ['title' => 'Correction path', 'description' => 'Cancel, replace, and correction operations are prepared in the contract layer.'],
            ],
        ],
        'payroll' => [
            'route' => 'vasaccounting.payroll.index',
            'path' => 'payroll',
            'permission' => 'vas_accounting.payroll.manage',
            'title' => 'Payroll Bridge',
            'nav_label' => 'Payroll',
            'subtitle' => 'Reuse Essentials payroll as the source and convert finalized runs into VAS postings.',
            'record_table' => 'vas_payroll_batches',
            'record_label' => 'Payroll batches',
            'provider_config_key' => 'payroll_bridge_adapters',
            'capabilities' => [
                ['title' => 'Essentials reuse', 'description' => 'Payroll entry remains in Essentials while finance posting stays in VAS.'],
                ['title' => 'Accrual and payment postings', 'description' => 'Separate payroll accrual and payment sequences can flow into the ledger.'],
                ['title' => 'Branch-aware payroll', 'description' => 'Payroll batches can be tied to locations and finance dimensions.'],
            ],
        ],
        'contracts' => [
            'route' => 'vasaccounting.contracts.index',
            'path' => 'contracts',
            'permission' => 'vas_accounting.contracts.manage',
            'title' => 'Contracts',
            'nav_label' => 'Contracts',
            'subtitle' => 'Contract registry, billing milestones, advances, retention, and attachment governance.',
            'record_table' => 'vas_contracts',
            'record_label' => 'Contracts',
            'capabilities' => [
                ['title' => 'Registry and metadata', 'description' => 'Track signed contracts with project, branch, and customer/vendor linkage.'],
                ['title' => 'Advance and retention', 'description' => 'Prepare contract accounting for advances and retained amounts.'],
                ['title' => 'Attachment governance', 'description' => 'Contracts can reuse the shared document attachment and audit foundations.'],
            ],
        ],
        'loans' => [
            'route' => 'vasaccounting.loans.index',
            'path' => 'loans',
            'permission' => 'vas_accounting.loans.manage',
            'title' => 'Loans',
            'nav_label' => 'Loans',
            'subtitle' => 'Loan agreements, disbursements, repayment plans, and interest accrual readiness.',
            'record_table' => 'vas_loans',
            'record_label' => 'Loans',
            'capabilities' => [
                ['title' => 'Loan register', 'description' => 'Track lender, principal, rate, maturity, and linked bank account details.'],
                ['title' => 'Debt-service preparation', 'description' => 'Prepare disbursement, repayment, and interest posting sequences.'],
                ['title' => 'Contract linkage', 'description' => 'Tie financing to contract or investment records when needed.'],
            ],
        ],
        'costing' => [
            'route' => 'vasaccounting.costing.index',
            'path' => 'costing',
            'permission' => 'vas_accounting.costing.manage',
            'title' => 'Cost Accounting',
            'nav_label' => 'Costing',
            'subtitle' => 'Departments, cost centers, projects, and WIP-ready finance dimensions.',
            'record_table' => 'vas_cost_centers',
            'record_label' => 'Cost centers',
            'capabilities' => [
                ['title' => 'Cost dimensions', 'description' => 'Departments, cost centers, and projects are ready on voucher lines and journals.'],
                ['title' => 'Project accumulation', 'description' => 'Capture costs against projects and cost objects for later rollups.'],
                ['title' => 'Period-close traceability', 'description' => 'Dimensions carry through into ledger and budget reporting.'],
            ],
        ],
        'budgets' => [
            'route' => 'vasaccounting.budgets.index',
            'path' => 'budgets',
            'permission' => 'vas_accounting.budgets.manage',
            'title' => 'Budgets',
            'nav_label' => 'Budgets',
            'subtitle' => 'Budget headers, line planning, commitments, actuals, and variance readiness.',
            'record_table' => 'vas_budgets',
            'record_label' => 'Budgets',
            'capabilities' => [
                ['title' => 'Budget structures', 'description' => 'Budget headers and line items can tie to account and cost dimensions.'],
                ['title' => 'Commitment tracking', 'description' => 'Reserved, committed, and actual balances can be tracked separately.'],
                ['title' => 'Variance reporting', 'description' => 'Budgets are prepared for budget-vs-actual reporting by period or project.'],
            ],
        ],
        'integrations' => [
            'route' => 'vasaccounting.integrations.index',
            'path' => 'integrations',
            'permission' => 'vas_accounting.integrations.manage',
            'title' => 'Integration Hub',
            'nav_label' => 'Integrations',
            'subtitle' => 'API guard normalization, provider adapters, import/export contracts, and external finance connectors.',
            'record_table' => 'vas_posting_failures',
            'record_label' => 'Integration events',
            'provider_config_key' => 'einvoice_adapters',
            'capabilities' => [
                ['title' => 'Provider managers', 'description' => 'Dedicated managers now resolve e-invoice, payroll, bank, and tax adapters.'],
                ['title' => 'API normalization', 'description' => 'VAS API routes now align to Passport guard usage for enterprise integrations.'],
                ['title' => 'Import/export readiness', 'description' => 'Shared contracts support opening balances, statements, tax exports, and payroll bridge flows.'],
            ],
        ],
    ],
    'mandatory_posting_map_keys' => [
        'cash',
        'bank',
        'accounts_receivable',
        'accounts_payable',
        'revenue',
        'vat_output',
        'vat_input',
        'inventory',
        'cogs',
        'expense',
        'fixed_asset',
        'accumulated_depreciation',
        'depreciation_expense',
        'stock_adjustment',
        'stock_transfer',
    ],
    'default_posting_map_codes' => [
        'cash' => '111',
        'bank' => '112',
        'accounts_receivable' => '131',
        'accounts_payable' => '331',
        'revenue' => '511',
        'vat_output' => '33311',
        'vat_input' => '1331',
        'inventory' => '156',
        'cogs' => '632',
        'expense' => '6427',
        'fixed_asset' => '211',
        'accumulated_depreciation' => '2141',
        'depreciation_expense' => '6424',
        'stock_adjustment' => '632',
        'stock_transfer' => '1368',
    ],
    'voucher_sequences' => [
        ['sequence_key' => 'general_journal', 'prefix' => 'JV', 'padding' => 5],
        ['sequence_key' => 'opening_balance', 'prefix' => 'OB', 'padding' => 5],
        ['sequence_key' => 'historical_treasury', 'prefix' => 'HIS', 'padding' => 5],
        ['sequence_key' => 'sales_invoice', 'prefix' => 'SV', 'padding' => 5],
        ['sequence_key' => 'purchase_invoice', 'prefix' => 'PV', 'padding' => 5],
        ['sequence_key' => 'cash_receipt', 'prefix' => 'CR', 'padding' => 5],
        ['sequence_key' => 'cash_payment', 'prefix' => 'CP', 'padding' => 5],
        ['sequence_key' => 'bank_receipt', 'prefix' => 'BR', 'padding' => 5],
        ['sequence_key' => 'bank_payment', 'prefix' => 'BP', 'padding' => 5],
        ['sequence_key' => 'fund_transfer', 'prefix' => 'FT', 'padding' => 5],
        ['sequence_key' => 'sales_credit_note', 'prefix' => 'SCN', 'padding' => 5],
        ['sequence_key' => 'purchase_debit_note', 'prefix' => 'PDN', 'padding' => 5],
        ['sequence_key' => 'depreciation', 'prefix' => 'DEP', 'padding' => 5],
        ['sequence_key' => 'tool_amortization', 'prefix' => 'TAM', 'padding' => 5],
        ['sequence_key' => 'inventory_receipt', 'prefix' => 'WR', 'padding' => 5],
        ['sequence_key' => 'inventory_issue', 'prefix' => 'WI', 'padding' => 5],
        ['sequence_key' => 'inventory_transfer', 'prefix' => 'WT', 'padding' => 5],
        ['sequence_key' => 'inventory_adjustment', 'prefix' => 'WA', 'padding' => 5],
        ['sequence_key' => 'payroll_accrual', 'prefix' => 'PAY', 'padding' => 5],
        ['sequence_key' => 'payroll_payment', 'prefix' => 'PYP', 'padding' => 5],
        ['sequence_key' => 'contract_accrual', 'prefix' => 'CTR', 'padding' => 5],
        ['sequence_key' => 'loan_disbursement', 'prefix' => 'LON', 'padding' => 5],
        ['sequence_key' => 'loan_repayment', 'prefix' => 'LRP', 'padding' => 5],
        ['sequence_key' => 'budget_adjustment', 'prefix' => 'BUD', 'padding' => 5],
        ['sequence_key' => 'tax_adjustment', 'prefix' => 'TAX', 'padding' => 5],
        ['sequence_key' => 'closing', 'prefix' => 'CLS', 'padding' => 5],
    ],
    'financial_statement_types' => [
        'balance_sheet' => ['label' => 'Balance Sheet'],
        'income_statement' => ['label' => 'Income Statement'],
        'cash_flow' => ['label' => 'Cash Flow Statement'],
        'notes' => ['label' => 'Notes to Financial Statements'],
    ],
    'financial_statement_lines' => [
        'tt99_2025' => [
            'balance_sheet' => [
                ['line_code' => 'A100', 'label' => 'Cash and cash equivalents', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['111', '112']],
                ['line_code' => 'A110', 'label' => 'Accounts receivable', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['131']],
                ['line_code' => 'A120', 'label' => 'Inventories', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['152', '153', '154', '155', '156', '157']],
                ['line_code' => 'A200', 'label' => 'Fixed assets (gross)', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['211', '212', '213', '217']],
                ['line_code' => 'A210', 'label' => 'Accumulated depreciation', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['214']],
                ['line_code' => 'L100', 'label' => 'Accounts payable', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['331']],
                ['line_code' => 'L110', 'label' => 'Taxes and other payables', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['333', '334', '335', '338']],
                ['line_code' => 'L120', 'label' => 'Loans and borrowings', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['311', '315', '341', '342', '343']],
                ['line_code' => 'E100', 'label' => 'Owner equity', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['411', '412', '418']],
                ['line_code' => 'E110', 'label' => 'Retained earnings', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['421']],
            ],
            'income_statement' => [
                ['line_code' => 'I100', 'label' => 'Revenue', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['511', '512', '515']],
                ['line_code' => 'I110', 'label' => 'Cost of goods sold', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['632']],
                ['line_code' => 'I120', 'label' => 'Gross profit', 'formula' => 'I100 - I110'],
                ['line_code' => 'I130', 'label' => 'Selling expenses', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['641']],
                ['line_code' => 'I140', 'label' => 'General and admin expenses', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['642']],
                ['line_code' => 'I150', 'label' => 'Finance costs', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['635']],
                ['line_code' => 'I160', 'label' => 'Other income', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['711']],
                ['line_code' => 'I170', 'label' => 'Other expenses', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['811']],
                ['line_code' => 'I180', 'label' => 'Corporate income tax expense', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['821']],
                ['line_code' => 'I190', 'label' => 'Profit after tax', 'formula' => 'I120 - I130 - I140 - I150 + I160 - I170 - I180'],
            ],
            'cash_flow' => [
                ['line_code' => 'C100', 'label' => 'Cash inflows from operating activities', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['111', '112'], 'source' => 'period'],
                ['line_code' => 'C110', 'label' => 'Cash outflows from operating activities', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['111', '112'], 'source' => 'period'],
                ['line_code' => 'C120', 'label' => 'Net cash flow from operating activities', 'formula' => 'C100 - C110'],
                ['line_code' => 'C200', 'label' => 'Opening cash and cash equivalents', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['111', '112'], 'source' => 'opening'],
                ['line_code' => 'C210', 'label' => 'Closing cash and cash equivalents', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['111', '112'], 'source' => 'closing'],
            ],
            'notes' => [
                ['line_code' => 'N100', 'label' => 'Reporting basis', 'type' => 'text', 'default_text' => 'Prepared under Circular 99/2025/TT-BTC effective January 1, 2026.'],
                ['line_code' => 'N110', 'label' => 'Book currency', 'type' => 'setting', 'setting_path' => 'book_currency'],
                ['line_code' => 'N120', 'label' => 'Inventory valuation method', 'type' => 'setting', 'setting_path' => 'inventory_method'],
                ['line_code' => 'N130', 'label' => 'Total active ledger accounts', 'type' => 'metric', 'metric' => 'active_accounts'],
            ],
        ],
        'tt200_legacy_bridge' => [
            'balance_sheet' => [
                ['line_code' => 'A100', 'label' => 'Cash and cash equivalents', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['111', '112']],
                ['line_code' => 'A110', 'label' => 'Accounts receivable', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['131']],
                ['line_code' => 'A120', 'label' => 'Inventories', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['152', '153', '154', '155', '156', '157']],
                ['line_code' => 'L100', 'label' => 'Accounts payable', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['331']],
                ['line_code' => 'E100', 'label' => 'Owner equity', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['411', '412', '418', '421']],
            ],
            'income_statement' => [
                ['line_code' => 'I100', 'label' => 'Revenue', 'normal' => 'credit_minus_debit', 'account_prefixes' => ['511', '512', '515']],
                ['line_code' => 'I110', 'label' => 'Cost of goods sold', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['632']],
                ['line_code' => 'I120', 'label' => 'Profit before tax', 'formula' => 'I100 - I110'],
            ],
            'cash_flow' => [
                ['line_code' => 'C100', 'label' => 'Opening cash and cash equivalents', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['111', '112'], 'source' => 'opening'],
                ['line_code' => 'C110', 'label' => 'Closing cash and cash equivalents', 'normal' => 'debit_minus_credit', 'account_prefixes' => ['111', '112'], 'source' => 'closing'],
            ],
        ],
    ],
    'source_document_adapters' => [
        'sell' => SellDocumentAdapter::class,
        'purchase' => PurchaseDocumentAdapter::class,
        'expense' => ExpenseDocumentAdapter::class,
        'transaction_payment' => PaymentDocumentAdapter::class,
        'sell_return' => SellReturnDocumentAdapter::class,
        'purchase_return' => PurchaseReturnDocumentAdapter::class,
        'stock_adjustment' => StockAdjustmentDocumentAdapter::class,
        'stock_transfer' => StockTransferDocumentAdapter::class,
        'opening_stock' => OpeningStockDocumentAdapter::class,
        'inventory_document' => InventoryDocumentAdapter::class,
    ],
    'einvoice_adapters' => [
        'sandbox' => SandboxEInvoiceAdapter::class,
        'vnpt' => VnptEInvoiceAdapter::class,
    ],
    'bank_statement_import_adapters' => [
        'manual' => NullBankStatementImportAdapter::class,
    ],
    'tax_export_adapters' => [
        'local' => LocalTaxExportAdapter::class,
        'vnpt' => VnptTaxExportAdapter::class,
    ],
    'payroll_bridge_adapters' => [
        'essentials' => EssentialsPayrollBridgeAdapter::class,
    ],
    'provider_health_profiles' => [
        'bank_statement_import' => [
            'manual' => [
                'label' => 'Manual bank import',
                'production_ready' => false,
                'required_config' => [],
                'notes' => 'Manual queue flow remains available, but a real bank provider is still required before final cutover.',
            ],
        ],
        'tax_export' => [
            'local' => [
                'label' => 'Local tax payload',
                'production_ready' => false,
                'required_config' => [],
                'notes' => 'Local export payloads are implemented, but filing-grade provider output is still required.',
            ],
            'vnpt' => [
                'label' => 'VNPT tax export',
                'production_ready' => true,
                'required_config' => [
                    'integration_settings.vnpt_api_base_url',
                    'integration_settings.vnpt_client_id',
                    'integration_settings.vnpt_client_secret',
                    'integration_settings.vnpt_tax_username',
                    'integration_settings.vnpt_tax_password',
                ],
                'notes' => 'VNPT filing-grade export is enabled when production credentials are present.',
            ],
        ],
        'einvoice' => [
            'sandbox' => [
                'label' => 'Sandbox e-invoice',
                'production_ready' => false,
                'required_config' => [],
                'notes' => 'Sandbox issuance is enabled for workflow testing only; production provider credentials are still required.',
            ],
            'vnpt' => [
                'label' => 'VNPT e-invoice',
                'production_ready' => true,
                'required_config' => [
                    'integration_settings.vnpt_api_base_url',
                    'integration_settings.vnpt_client_id',
                    'integration_settings.vnpt_client_secret',
                ],
                'notes' => 'VNPT production issuance is available after credential validation and provider health checks.',
            ],
        ],
        'payroll_bridge' => [
            'essentials' => [
                'label' => 'Essentials payroll bridge',
                'production_ready' => true,
                'required_config' => [],
                'notes' => 'Payroll bridge stays manual and queue-backed inside VAS.',
            ],
        ],
    ],
    'page_sections' => [
        'core' => [
            'label' => 'Core Ledger',
            'badge_variant' => 'light-primary',
        ],
        'operations' => [
            'label' => 'Operations',
            'badge_variant' => 'light-success',
        ],
        'planning' => [
            'label' => 'Planning',
            'badge_variant' => 'light-info',
        ],
        'controls' => [
            'label' => 'Controls',
            'badge_variant' => 'light-warning',
        ],
    ],
    'page_registry' => [
        'vasaccounting.setup.index' => [
            'title' => 'VAS Accounting Setup',
            'nav_label' => 'Setup',
            'subtitle' => 'Business configuration, compliance defaults, and posting-map readiness.',
            'icon' => 'ki-outline ki-setting-2',
            'section_group' => 'core',
            'permission' => 'vas_accounting.access',
            'show_in_nav' => true,
            'nav_sort' => 10,
            'active_pattern' => 'vasaccounting.setup.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.dashboard.index', 'label' => 'Open dashboard', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.dashboard.index' => [
            'title' => 'Accounting Dashboard',
            'nav_label' => 'Dashboard',
            'subtitle' => 'Posting health, close readiness, and statutory activity in one command center.',
            'icon' => 'ki-outline ki-element-11',
            'section_group' => 'core',
            'permission' => 'vas_accounting.access',
            'show_in_nav' => true,
            'nav_sort' => 20,
            'active_pattern' => 'vasaccounting.dashboard.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.vouchers.create', 'label' => 'New voucher', 'style' => 'primary'],
                ['route' => 'vasaccounting.reports.index', 'label' => 'Open reports', 'style' => 'light-primary'],
                ['route' => 'vasaccounting.closing.index', 'label' => 'Period close', 'style' => 'light-warning'],
            ],
        ],
        'vasaccounting.chart.index' => [
            'title' => 'Chart of Accounts',
            'nav_label' => 'Chart',
            'subtitle' => 'Ledger structure, hierarchy controls, and account readiness for all VAS domains.',
            'icon' => 'ki-outline ki-chart-line-up-2',
            'section_group' => 'core',
            'permission' => 'vas_accounting.access',
            'show_in_nav' => true,
            'nav_sort' => 30,
            'active_pattern' => 'vasaccounting.chart.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.vouchers.create', 'label' => 'New voucher', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.periods.index' => [
            'title' => 'Accounting Periods',
            'nav_label' => 'Periods',
            'subtitle' => 'Fiscal calendars, open/close states, and close-readiness checkpoints.',
            'icon' => 'ki-outline ki-calendar-8',
            'section_group' => 'core',
            'permission' => 'vas_accounting.access',
            'show_in_nav' => true,
            'nav_sort' => 40,
            'active_pattern' => 'vasaccounting.periods.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.closing.index', 'label' => 'Go to closing', 'style' => 'light-warning'],
            ],
        ],
        'vasaccounting.vouchers.index' => [
            'title' => 'Voucher Register',
            'nav_label' => 'Vouchers',
            'subtitle' => 'Journal documents, workflow states, and posting activity across the VAS ledger.',
            'icon' => 'ki-outline ki-note-2',
            'section_group' => 'core',
            'permission' => 'vas_accounting.access',
            'show_in_nav' => true,
            'nav_sort' => 50,
            'active_pattern' => 'vasaccounting.vouchers.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.vouchers.create', 'label' => 'Create voucher', 'style' => 'primary'],
                ['route' => 'vasaccounting.reports.general_ledger', 'label' => 'General ledger', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.vouchers.create' => [
            'title' => 'Create Voucher',
            'subtitle' => 'Capture a balanced journal entry with dimensions, tax, and workflow status.',
            'icon' => 'ki-outline ki-notepad-edit',
            'section_group' => 'core',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.vouchers.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.vouchers.index', 'label' => 'Back to register', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.vouchers.show' => [
            'title' => 'Voucher Detail',
            'subtitle' => 'Review ledger lines, approvals, and posting actions for this journal document.',
            'icon' => 'ki-outline ki-file-sheet',
            'section_group' => 'core',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.vouchers.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.vouchers.index', 'label' => 'Back to register', 'style' => 'light-primary'],
                ['route' => 'vasaccounting.vouchers.create', 'label' => 'Create voucher', 'style' => 'primary'],
            ],
        ],
        'vasaccounting.cash_bank.index' => [
            'title' => 'Cash & Bank',
            'nav_label' => 'Cash & Bank',
            'subtitle' => 'Cashbooks, bank masters, statement imports, and reconciliation queues tied to posted vouchers.',
            'icon' => 'ki-outline ki-bank',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.cash_bank.manage',
            'feature_flag' => 'cash_bank',
            'show_in_nav' => true,
            'nav_sort' => 10,
            'active_pattern' => 'vasaccounting.cash_bank.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.cash_book', 'label' => 'Cash book', 'style' => 'light-primary'],
                ['route' => 'vasaccounting.reports.bank_reconciliation', 'label' => 'Reconciliation', 'style' => 'light-warning'],
            ],
        ],
        'vasaccounting.payment_documents.index' => [
            'title' => 'Payment Documents',
            'subtitle' => 'Native receipts and payments with draft, approval, posting, and allocation-ready status tracking.',
            'icon' => 'ki-outline ki-wallet',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.cash_bank.manage',
            'active_pattern' => 'vasaccounting.payment_documents.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.payment_documents.create', 'label' => 'Create payment', 'style' => 'primary'],
                ['route' => 'vasaccounting.cash_bank.index', 'label' => 'Cash & bank', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.payment_documents.create' => [
            'title' => 'Create Payment Document',
            'subtitle' => 'Capture a native receipt or payment draft with liquidity source and settlement targets.',
            'icon' => 'ki-outline ki-notepad-edit',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.cash_bank.manage',
            'active_pattern' => 'vasaccounting.payment_documents.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.payment_documents.index', 'label' => 'Back to payments', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.payment_documents.show' => [
            'title' => 'Payment Document Detail',
            'subtitle' => 'Review settlement targets, approval state, journal lines, and posting actions for a native payment document.',
            'icon' => 'ki-outline ki-file-sheet',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.cash_bank.manage',
            'active_pattern' => 'vasaccounting.payment_documents.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.payment_documents.index', 'label' => 'Back to payments', 'style' => 'light-primary'],
                ['route' => 'vasaccounting.cash_bank.index', 'label' => 'Cash & bank', 'style' => 'light-warning'],
            ],
        ],
        'vasaccounting.receivables.index' => [
            'title' => 'Receivables',
            'nav_label' => 'Receivables',
            'subtitle' => 'Customer aging, allocations, and collection readiness from VAS-linked documents.',
            'icon' => 'ki-outline ki-credit-cart',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.receivables.manage',
            'feature_flag' => 'receivables',
            'show_in_nav' => true,
            'nav_sort' => 20,
            'active_pattern' => 'vasaccounting.receivables.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.receivables', 'label' => 'Aging report', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.procurement.index' => [
            'title' => 'Procurement Workspace',
            'nav_label' => 'Procurement',
            'subtitle' => 'Native purchase requisitions, orders, goods receipts, and supplier invoices on the canonical finance workflow.',
            'icon' => 'ki-outline ki-delivery',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.procurement.manage',
            'feature_flag' => 'p2p_v2',
            'show_in_nav' => true,
            'nav_sort' => 25,
            'active_pattern' => 'vasaccounting.procurement.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.payables.index', 'label' => 'Payables', 'style' => 'light-primary'],
                ['route' => 'vasaccounting.inventory.index', 'label' => 'Inventory', 'style' => 'light-warning'],
            ],
        ],
        'vasaccounting.payables.index' => [
            'title' => 'Payables',
            'nav_label' => 'Payables',
            'subtitle' => 'Supplier liabilities, settlement allocations, and payment readiness.',
            'icon' => 'ki-outline ki-wallet',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.payables.manage',
            'feature_flag' => 'payables',
            'show_in_nav' => true,
            'nav_sort' => 30,
            'active_pattern' => 'vasaccounting.payables.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.payables', 'label' => 'Aging report', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.invoices.index' => [
            'title' => 'Invoice Register',
            'nav_label' => 'Invoices',
            'subtitle' => 'Sales and purchase invoices, notes, and downstream tax and e-invoice handoff.',
            'icon' => 'ki-outline ki-file-added',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.invoices.manage',
            'feature_flag' => 'invoices',
            'show_in_nav' => true,
            'nav_sort' => 40,
            'active_pattern' => 'vasaccounting.invoices.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.invoices.create', 'label' => 'Create purchase invoice', 'style' => 'primary'],
                ['route' => 'vasaccounting.einvoices.index', 'label' => 'E-invoices', 'style' => 'light-primary', 'feature_flag' => 'einvoices'],
                ['route' => 'vasaccounting.tax.index', 'label' => 'Tax center', 'style' => 'light-warning', 'feature_flag' => 'tax'],
            ],
        ],
        'vasaccounting.invoices.create' => [
            'title' => 'Create Purchase Invoice',
            'subtitle' => 'Capture a native AP invoice or debit note draft with line-level account distribution and VAT handling.',
            'icon' => 'ki-outline ki-notepad-edit',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.invoices.manage',
            'active_pattern' => 'vasaccounting.invoices.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.invoices.index', 'label' => 'Back to invoice register', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.invoices.show' => [
            'title' => 'Invoice Detail',
            'subtitle' => 'Review native AP draft, approval progress, and posting readiness before settlement.',
            'icon' => 'ki-outline ki-file-sheet',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.invoices.manage',
            'active_pattern' => 'vasaccounting.invoices.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.invoices.index', 'label' => 'Back to invoice register', 'style' => 'light-primary'],
                ['route' => 'vasaccounting.payment_documents.create', 'label' => 'Create payment', 'style' => 'light-warning'],
            ],
        ],
        'vasaccounting.inventory.index' => [
            'title' => 'Warehouse & Inventory',
            'nav_label' => 'Inventory',
            'subtitle' => 'Warehouse accounting, valuation, movement traceability, and stock reconciliation.',
            'icon' => 'ki-outline ki-package',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.inventory.manage',
            'feature_flag' => 'inventory',
            'show_in_nav' => true,
            'nav_sort' => 50,
            'active_pattern' => 'vasaccounting.inventory.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.inventory', 'label' => 'Inventory report', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.expenses.index' => [
            'title' => 'Expense Management',
            'nav_label' => 'Expenses',
            'subtitle' => 'Native expense claims, employee advances, settlements, and reimbursements on the finance-core workflow.',
            'icon' => 'ki-outline ki-wallet',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.expenses.manage',
            'feature_flag' => 'expense_v2',
            'show_in_nav' => true,
            'nav_sort' => 55,
            'active_pattern' => 'vasaccounting.expenses.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.payables', 'label' => 'Payables report', 'style' => 'light-primary'],
                ['route' => 'vasaccounting.cash_bank.index', 'label' => 'Cash & bank', 'style' => 'light-warning'],
            ],
        ],
        'vasaccounting.tools.index' => [
            'title' => 'Tools & Instruments',
            'nav_label' => 'Tools',
            'subtitle' => 'Tool registers, amortization schedules, and remaining-value control by operational dimension.',
            'icon' => 'ki-outline ki-wrench',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.tools.manage',
            'feature_flag' => 'tools',
            'show_in_nav' => true,
            'nav_sort' => 60,
            'active_pattern' => 'vasaccounting.tools.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.operational_health', 'label' => 'Operational health', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.assets.index' => [
            'title' => 'Fixed Assets',
            'nav_label' => 'Assets',
            'subtitle' => 'Asset register, depreciation, transfer, and disposal workflows for long-lived items.',
            'icon' => 'ki-outline ki-office-bag',
            'section_group' => 'operations',
            'permission' => 'vas_accounting.assets.manage',
            'feature_flag' => 'assets',
            'show_in_nav' => true,
            'nav_sort' => 70,
            'active_pattern' => 'vasaccounting.assets.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.fixed_assets', 'label' => 'Asset report', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.tax.index' => [
            'title' => 'Tax Center',
            'nav_label' => 'Tax',
            'subtitle' => 'Tax codes, summaries, declaration exports, and audit-ready tax controls.',
            'icon' => 'ki-outline ki-chart-pie-4',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.tax.manage',
            'feature_flag' => 'tax',
            'show_in_nav' => true,
            'nav_sort' => 20,
            'active_pattern' => 'vasaccounting.tax.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.vat', 'label' => 'VAT report', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.einvoices.index' => [
            'title' => 'E-Invoices',
            'nav_label' => 'E-Invoices',
            'subtitle' => 'Provider issue, sync, correction, and replacement workflows for invoice documents.',
            'icon' => 'ki-outline ki-message-text-2',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.einvoices.manage',
            'feature_flag' => 'einvoices',
            'show_in_nav' => true,
            'nav_sort' => 30,
            'active_pattern' => 'vasaccounting.einvoices.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.invoices.index', 'label' => 'Invoice register', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.payroll.index' => [
            'title' => 'Payroll Bridge',
            'nav_label' => 'Payroll',
            'subtitle' => 'Finalize payroll batches and convert them into VAS accrual and payment postings.',
            'icon' => 'ki-outline ki-briefcase',
            'section_group' => 'planning',
            'permission' => 'vas_accounting.payroll.manage',
            'feature_flag' => 'payroll',
            'show_in_nav' => true,
            'nav_sort' => 10,
            'active_pattern' => 'vasaccounting.payroll.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.payroll_bridge', 'label' => 'Payroll report', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.contracts.index' => [
            'title' => 'Contracts',
            'nav_label' => 'Contracts',
            'subtitle' => 'Contract registry, milestone billing, retention, and commercial accounting controls.',
            'icon' => 'ki-outline ki-file-right',
            'section_group' => 'planning',
            'permission' => 'vas_accounting.contracts.manage',
            'feature_flag' => 'contracts',
            'show_in_nav' => true,
            'nav_sort' => 20,
            'active_pattern' => 'vasaccounting.contracts.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.contracts', 'label' => 'Contract report', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.loans.index' => [
            'title' => 'Loans',
            'nav_label' => 'Loans',
            'subtitle' => 'Loan agreements, repayment schedules, and debt-service posting readiness.',
            'icon' => 'ki-outline ki-dollar',
            'section_group' => 'planning',
            'permission' => 'vas_accounting.loans.manage',
            'feature_flag' => 'loans',
            'show_in_nav' => true,
            'nav_sort' => 30,
            'active_pattern' => 'vasaccounting.loans.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.loans', 'label' => 'Loan report', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.costing.index' => [
            'title' => 'Cost Accounting',
            'nav_label' => 'Costing',
            'subtitle' => 'Departments, cost centers, projects, and dimension structures for allocations and reporting.',
            'icon' => 'ki-outline ki-chart-simple-3',
            'section_group' => 'planning',
            'permission' => 'vas_accounting.costing.manage',
            'feature_flag' => 'costing',
            'show_in_nav' => true,
            'nav_sort' => 40,
            'active_pattern' => 'vasaccounting.costing.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.costing', 'label' => 'Costing report', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.budgets.index' => [
            'title' => 'Budgets',
            'nav_label' => 'Budgets',
            'subtitle' => 'Budget headers, planning lines, actual sync, and variance monitoring.',
            'icon' => 'ki-outline ki-abstract-26',
            'section_group' => 'planning',
            'permission' => 'vas_accounting.budgets.manage',
            'feature_flag' => 'budgets',
            'show_in_nav' => true,
            'nav_sort' => 50,
            'active_pattern' => 'vasaccounting.budgets.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.budget_variance', 'label' => 'Variance report', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.integrations.index' => [
            'title' => 'Integration Hub',
            'nav_label' => 'Integrations',
            'subtitle' => 'Provider adapters, run history, retries, and external finance connector health.',
            'icon' => 'ki-outline ki-arrows-circle',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.integrations.manage',
            'feature_flag' => 'integrations',
            'show_in_nav' => true,
            'nav_sort' => 40,
            'active_pattern' => 'vasaccounting.integrations.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.cutover.index', 'label' => 'Cutover board', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.closing.index' => [
            'title' => 'Period Close',
            'nav_label' => 'Closing',
            'subtitle' => 'Close blockers, readiness gates, and month-end control actions.',
            'icon' => 'ki-outline ki-shield-tick',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'show_in_nav' => true,
            'nav_sort' => 10,
            'active_pattern' => 'vasaccounting.closing.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.close_packet', 'label' => 'Close packet', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.cutover.index' => [
            'title' => 'Cutover Governance',
            'nav_label' => 'Cutover',
            'subtitle' => 'Readiness, branch rollout, parity review, and legacy transition governance.',
            'icon' => 'ki-outline ki-rocket',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.cutover.manage',
            'show_in_nav' => true,
            'nav_sort' => 50,
            'active_pattern' => 'vasaccounting.cutover.*',
            'supports_location_filter' => true,
            'quick_actions' => [
                ['route' => 'vasaccounting.integrations.index', 'label' => 'Integration hub', 'style' => 'light-primary', 'feature_flag' => 'integrations'],
            ],
        ],
        'vasaccounting.reports.index' => [
            'title' => 'Reports',
            'nav_label' => 'Reports',
            'subtitle' => 'Enterprise reporting hub with live views, snapshots, and close-ready report packs.',
            'icon' => 'ki-outline ki-chart-simple',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'show_in_nav' => true,
            'nav_sort' => 60,
            'active_pattern' => 'vasaccounting.reports.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.trial_balance', 'label' => 'Trial balance', 'style' => 'primary'],
                ['route' => 'vasaccounting.reports.financial_statements', 'label' => 'Financial statements', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.reports.snapshots.show' => [
            'title' => 'Report Snapshot',
            'subtitle' => 'Saved reporting output captured for approvals, review, and period-close evidence.',
            'icon' => 'ki-outline ki-document',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
            'quick_actions' => [
                ['route' => 'vasaccounting.reports.index', 'label' => 'Back to reports', 'style' => 'light-primary'],
            ],
        ],
        'vasaccounting.reports.trial_balance' => [
            'title' => 'Trial Balance',
            'subtitle' => 'Trial balance output with period and account-level drill-through.',
            'icon' => 'ki-outline ki-chart-line',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.general_ledger' => [
            'title' => 'General Ledger',
            'subtitle' => 'Ledger activity by account with document, period, and posting references.',
            'icon' => 'ki-outline ki-book-open',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.vat' => [
            'title' => 'VAT Report',
            'subtitle' => 'Output and input VAT datasets prepared for declaration and audit support.',
            'icon' => 'ki-outline ki-receipt-square',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.cash_book' => [
            'title' => 'Cash Book',
            'subtitle' => 'Cash movement analysis tied to VAS voucher activity.',
            'icon' => 'ki-outline ki-wallet',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.bank_book' => [
            'title' => 'Bank Book',
            'subtitle' => 'Bank movement reporting with account, import, and posting references.',
            'icon' => 'ki-outline ki-bank',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.bank_reconciliation' => [
            'title' => 'Bank Reconciliation',
            'subtitle' => 'Statement matching, unmatched lines, and reconciliation exceptions.',
            'icon' => 'ki-outline ki-arrows-loop',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.receivables' => [
            'title' => 'Receivables Aging',
            'subtitle' => 'Customer balance and collection exposure by due status.',
            'icon' => 'ki-outline ki-credit-cart',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.payables' => [
            'title' => 'Payables Aging',
            'subtitle' => 'Supplier exposure and payment timing across open liabilities.',
            'icon' => 'ki-outline ki-wallet',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.invoice_register' => [
            'title' => 'Invoice Register',
            'subtitle' => 'Invoice, credit-note, and debit-note activity prepared for finance review.',
            'icon' => 'ki-outline ki-file-added',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.inventory' => [
            'title' => 'Inventory Report',
            'subtitle' => 'Warehouse stock and valuation output aligned to the ledger.',
            'icon' => 'ki-outline ki-package',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.fixed_assets' => [
            'title' => 'Fixed Asset Report',
            'subtitle' => 'Register, depreciation, and net-book-value visibility for assets.',
            'icon' => 'ki-outline ki-office-bag',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.payroll_bridge' => [
            'title' => 'Payroll Bridge Report',
            'subtitle' => 'Payroll batches, accruals, and payment bridge activity.',
            'icon' => 'ki-outline ki-briefcase',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.contracts' => [
            'title' => 'Contracts Report',
            'subtitle' => 'Contract commitments, milestones, and billing posture across the register.',
            'icon' => 'ki-outline ki-file-right',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.loans' => [
            'title' => 'Loans Report',
            'subtitle' => 'Loan portfolio, maturities, and repayment plan status.',
            'icon' => 'ki-outline ki-dollar',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.costing' => [
            'title' => 'Costing Report',
            'subtitle' => 'Department, cost-center, and project structures prepared for analysis.',
            'icon' => 'ki-outline ki-chart-simple-3',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.budget_variance' => [
            'title' => 'Budget Variance',
            'subtitle' => 'Budget versus actual visibility across periods and dimensions.',
            'icon' => 'ki-outline ki-abstract-26',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.financial_statements' => [
            'title' => 'Financial Statements',
            'subtitle' => 'Statement outputs prepared for management review and statutory close.',
            'icon' => 'ki-outline ki-chart-line-star',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.close_packet' => [
            'title' => 'Close Packet',
            'subtitle' => 'Month-end reporting pack for close governance and approvals.',
            'icon' => 'ki-outline ki-folder',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
        'vasaccounting.reports.operational_health' => [
            'title' => 'Operational Health',
            'subtitle' => 'Operational finance signal tracking across queues, providers, and blockers.',
            'icon' => 'ki-outline ki-pulse',
            'section_group' => 'controls',
            'permission' => 'vas_accounting.access',
            'active_pattern' => 'vasaccounting.reports.*',
        ],
    ],
    'tax_codes' => [
        ['code' => 'VAT10_OUT', 'name' => 'VAT Output 10%', 'direction' => 'output', 'rate' => 10.0],
        ['code' => 'VAT10_IN', 'name' => 'VAT Input 10%', 'direction' => 'input', 'rate' => 10.0],
        ['code' => 'VAT8_OUT', 'name' => 'VAT Output 8%', 'direction' => 'output', 'rate' => 8.0],
        ['code' => 'VAT8_IN', 'name' => 'VAT Input 8%', 'direction' => 'input', 'rate' => 8.0],
        ['code' => 'VAT0_OUT', 'name' => 'VAT Output 0%', 'direction' => 'output', 'rate' => 0.0],
        ['code' => 'VAT_EXEMPT', 'name' => 'VAT Exempt', 'direction' => 'both', 'rate' => 0.0],
    ],
    'vn_chart' => require __DIR__ . '/vn_chart.php',
];
