<?php

use Modules\VasAccounting\Services\Adapters\ExpenseDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\EssentialsPayrollBridgeAdapter;
use Modules\VasAccounting\Services\Adapters\LocalTaxExportAdapter;
use Modules\VasAccounting\Services\Adapters\NullBankStatementImportAdapter;
use Modules\VasAccounting\Services\Adapters\OpeningStockDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\PaymentDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\PurchaseDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\PurchaseReturnDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\SellDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\SellReturnDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\StockAdjustmentDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\StockTransferDocumentAdapter;
use Modules\VasAccounting\Services\Adapters\SandboxEInvoiceAdapter;

return [
    'version' => '1.1.0',
    'business_module_key' => 'vas_accounting',
    'book_currency' => 'VND',
    'inventory_method' => 'weighted_average',
    'default_timezone' => 'Asia/Ho_Chi_Minh',
    'api_guard' => 'auth:api',
    'report_route_prefix' => 'vas-accounting/reports',
    'document_statuses' => [
        'draft' => 'Draft',
        'pending_approval' => 'Pending approval',
        'approved' => 'Approved',
        'posted' => 'Posted',
        'reversed' => 'Reversed',
        'cancelled' => 'Cancelled',
    ],
    'period_statuses' => [
        'open' => 'Open',
        'soft_locked' => 'Soft locked',
        'closed' => 'Closed',
    ],
    'feature_flags' => [
        'cash_bank' => true,
        'receivables' => true,
        'payables' => true,
        'invoices' => true,
        'inventory' => true,
        'tools' => true,
        'assets' => true,
        'tax' => true,
        'einvoices' => true,
        'payroll' => true,
        'contracts' => true,
        'loans' => true,
        'costing' => true,
        'budgets' => true,
        'integrations' => true,
        'reports' => true,
        'closing' => true,
    ],
    'cutover_defaults' => [
        'legacy_routes_mode' => 'observe',
        'hide_legacy_accounting_menu' => false,
        'parallel_run_status' => 'not_started',
        'parallel_run_notes' => null,
        'uat_statuses' => [],
        'last_parity_check_at' => null,
        'last_legacy_redirect_at' => null,
    ],
    'rollout_defaults' => [
        'status' => 'pilot',
        'target_go_live_date' => null,
        'support_owner' => null,
        'training_notes' => null,
        'enabled_branch_ids' => [],
        'rollout_notes' => null,
    ],
    'cutover_uat_personas' => [
        'accountant' => [
            'label' => 'Accountant',
            'description' => 'Validate trial balance, financial statements, close packet generation, and reversal controls.',
            'focus_area' => 'Core ledger and statutory reports',
        ],
        'cashier' => [
            'label' => 'Cashier',
            'description' => 'Validate cashbooks, bank accounts, statement import, reconciliation actions, and payment flows.',
            'focus_area' => 'Cash, cashier, and bank operations',
        ],
        'ap_ar_clerk' => [
            'label' => 'AP/AR clerk',
            'description' => 'Validate invoice register, allocations, aging reports, and collection or payment readiness.',
            'focus_area' => 'Receivables, payables, and invoice settlement',
        ],
        'warehouse_accountant' => [
            'label' => 'Warehouse accountant',
            'description' => 'Validate warehouse masters, valuation views, and inventory report reproducibility by branch.',
            'focus_area' => 'Warehouse and inventory accounting',
        ],
        'tax_accountant' => [
            'label' => 'Tax accountant',
            'description' => 'Validate VAT books, tax export payloads, and e-invoice traceability.',
            'focus_area' => 'Tax center and e-invoice readiness',
        ],
        'payroll_accountant' => [
            'label' => 'Payroll accountant',
            'description' => 'Validate payroll bridge accruals, payroll payment bridge, and downstream reporting.',
            'focus_area' => 'Payroll bridge and finance postings',
        ],
        'finance_manager' => [
            'label' => 'Finance manager',
            'description' => 'Validate close controls, report snapshots, integration operations, and cutover readiness.',
            'focus_area' => 'Governance, close, and rollout oversight',
        ],
        'branch_manager' => [
            'label' => 'Branch manager',
            'description' => 'Validate branch filtering, enabled rollout branches, and branch-level cash and document coverage.',
            'focus_area' => 'Branch rollout and operational sign-off',
        ],
    ],
    'legacy_accounting_route_map' => [
        'account' => [
            'legacy_label' => 'Legacy account register and transaction maintenance',
            'legacy_paths' => ['account/account', 'account/account/*', 'account/fund-transfer/*', 'account/deposit/*', 'account/close/*', 'account/activate/*', 'account/delete-account-transaction/*', 'account/edit-account-transaction/*', 'account/update-account-transaction/*', 'account/get-account-balance/*'],
            'route' => 'vasaccounting.cash_bank.index',
            'target_label' => 'VAS Cash & Bank',
        ],
        'balance-sheet' => [
            'legacy_label' => 'Legacy balance sheet report',
            'legacy_paths' => ['account/balance-sheet'],
            'route' => 'vasaccounting.reports.financial_statements',
            'target_label' => 'VAS Financial Statements',
            'query' => ['statement' => 'balance_sheet'],
        ],
        'trial-balance' => [
            'legacy_label' => 'Legacy trial balance report',
            'legacy_paths' => ['account/trial-balance'],
            'route' => 'vasaccounting.reports.trial_balance',
            'target_label' => 'VAS Trial Balance',
        ],
        'payment-account-report' => [
            'legacy_label' => 'Legacy payment account report',
            'legacy_paths' => ['account/payment-account-report'],
            'route' => 'vasaccounting.reports.bank_book',
            'target_label' => 'VAS Bank Book',
        ],
        'link-account' => [
            'legacy_label' => 'Legacy account-linking workflow',
            'legacy_paths' => ['account/link-account/*'],
            'route' => 'vasaccounting.cash_bank.index',
            'target_label' => 'VAS Cash & Bank',
        ],
        'cash-flow' => [
            'legacy_label' => 'Legacy cash flow report',
            'legacy_paths' => ['account/cash-flow'],
            'route' => 'vasaccounting.reports.financial_statements',
            'target_label' => 'VAS Financial Statements',
            'query' => ['statement' => 'cash_flow'],
        ],
        'account-types' => [
            'legacy_label' => 'Legacy account type maintenance',
            'legacy_paths' => ['account-types', 'account-types/*'],
            'route' => 'vasaccounting.chart.index',
            'target_label' => 'VAS Chart of Accounts',
        ],
    ],
    'module_area_by_source' => [
        'manual' => 'accounting',
        'transaction_payment' => 'cash_bank',
        'sell' => 'invoices',
        'sell_return' => 'receivables',
        'purchase' => 'payables',
        'purchase_return' => 'payables',
        'expense' => 'payables',
        'stock_adjustment' => 'inventory',
        'stock_transfer' => 'inventory',
        'opening_stock' => 'inventory',
        'payroll' => 'payroll',
    ],
    'enterprise_domains' => [
        'cash_bank' => [
            'route' => 'vasaccounting.cash_bank.index',
            'path' => 'cash-bank',
            'permission' => 'vas_accounting.cash_bank.manage',
            'title' => 'Cash, Cashier & Bank',
            'nav_label' => 'Cash & Bank',
            'subtitle' => 'Cashbooks, cashier sessions, bank accounts, deposits, fund transfers, and reconciliation queues.',
            'record_table' => 'vas_cashbooks',
            'record_label' => 'Cashbooks',
            'provider_config_key' => 'bank_statement_import_adapters',
            'capabilities' => [
                ['title' => 'Cashbooks & teller control', 'description' => 'Branch-aware cashbooks and cashier accountability for daily opening and close.'],
                ['title' => 'Bank reconciliation', 'description' => 'Statement import, match queues, and reconciliation exceptions connected to posted vouchers.'],
                ['title' => 'Fund movement lifecycle', 'description' => 'Receipts, payments, deposits, and transfers follow the same approval and posting path.'],
            ],
        ],
        'receivables' => [
            'route' => 'vasaccounting.receivables.index',
            'path' => 'receivables',
            'permission' => 'vas_accounting.receivables.manage',
            'title' => 'Receivables',
            'nav_label' => 'Receivables',
            'subtitle' => 'Customer subledger allocations, statements, aging, and collection workflows.',
            'record_table' => 'vas_receivable_allocations',
            'record_label' => 'AR allocations',
            'capabilities' => [
                ['title' => 'Settlement allocation', 'description' => 'Match receipts against invoices and keep residual balances visible by customer.'],
                ['title' => 'Customer statements', 'description' => 'Prepare customer statements and aging views from VAS-ledger allocations.'],
                ['title' => 'Credit control', 'description' => 'Surface overdue items and approval queues before period close.'],
            ],
        ],
        'payables' => [
            'route' => 'vasaccounting.payables.index',
            'path' => 'payables',
            'permission' => 'vas_accounting.payables.manage',
            'title' => 'Payables',
            'nav_label' => 'Payables',
            'subtitle' => 'Vendor bills, settlements, allocation tracking, and supplier aging.',
            'record_table' => 'vas_payable_allocations',
            'record_label' => 'AP allocations',
            'capabilities' => [
                ['title' => 'Bill settlement', 'description' => 'Allocate vendor payments across bills, returns, and expense settlements.'],
                ['title' => 'Vendor aging', 'description' => 'Surface current and overdue liabilities with branch-aware filters.'],
                ['title' => 'Payment readiness', 'description' => 'Keep payable balances tied to posted vouchers and approval status.'],
            ],
        ],
        'invoices' => [
            'route' => 'vasaccounting.invoices.index',
            'path' => 'invoices',
            'permission' => 'vas_accounting.invoices.manage',
            'title' => 'Sales & Purchase Invoices',
            'nav_label' => 'Invoices',
            'subtitle' => 'Sales invoices, purchase invoices, credit notes, debit notes, and document controls.',
            'record_table' => 'vas_vouchers',
            'record_label' => 'Invoice vouchers',
            'capabilities' => [
                ['title' => 'Invoice lifecycle', 'description' => 'Draft, approval, post, reversal, and cancellation all follow one document model.'],
                ['title' => 'Credit and debit notes', 'description' => 'Returns and adjustments stay linked to the original document chain.'],
                ['title' => 'Branch numbering', 'description' => 'Document numbering is ready for branch and period-aware expansion.'],
            ],
        ],
        'inventory' => [
            'route' => 'vasaccounting.inventory.index',
            'path' => 'inventory',
            'permission' => 'vas_accounting.inventory.manage',
            'title' => 'Warehouse & Inventory',
            'nav_label' => 'Inventory',
            'subtitle' => 'Warehouse accounting, valuation, movement traceability, and stock reconciliation.',
            'record_table' => 'vas_warehouses',
            'record_label' => 'Warehouses',
            'capabilities' => [
                ['title' => 'Warehouse masters', 'description' => 'Track warehouse structures alongside branch locations for inventory accounting.'],
                ['title' => 'Movement accounting', 'description' => 'Receipts, issues, adjustments, and transfers map cleanly into the ledger.'],
                ['title' => 'Close-ready valuation', 'description' => 'Inventory valuation remains reproducible by period and warehouse.'],
            ],
        ],
        'tools' => [
            'route' => 'vasaccounting.tools.index',
            'path' => 'tools',
            'permission' => 'vas_accounting.tools.manage',
            'title' => 'Tools & Instruments',
            'nav_label' => 'Tools',
            'subtitle' => 'Tool registers, issue tracking, amortization schedules, and remaining value control.',
            'record_table' => 'vas_tools',
            'record_label' => 'Tools',
            'capabilities' => [
                ['title' => 'Register & issuance', 'description' => 'Track tools from acquisition through issue to departments, projects, or branches.'],
                ['title' => 'Amortization', 'description' => 'Prepare periodic expense recognition for tools and instruments.'],
                ['title' => 'Control dimensions', 'description' => 'Attach tool usage to department, cost center, and project dimensions.'],
            ],
        ],
        'assets' => [
            'route' => 'vasaccounting.assets.index',
            'path' => 'fixed-assets',
            'permission' => 'vas_accounting.assets.manage',
            'title' => 'Fixed Assets',
            'nav_label' => 'Assets',
            'subtitle' => 'Asset register, capitalization, depreciation, transfer, and disposal workflows.',
            'record_table' => 'vas_fixed_assets',
            'record_label' => 'Fixed assets',
            'capabilities' => [
                ['title' => 'Asset register', 'description' => 'Track acquisitions, useful life, depreciation, and disposal references.'],
                ['title' => 'Depreciation control', 'description' => 'Keep monthly depreciation tied to period close blockers and vouchers.'],
                ['title' => 'Lifecycle traceability', 'description' => 'Prepare transfer and disposal events without leaving the VAS ledger.'],
            ],
        ],
        'tax' => [
            'route' => 'vasaccounting.tax.index',
            'path' => 'tax',
            'permission' => 'vas_accounting.tax.manage',
            'title' => 'Tax Center',
            'nav_label' => 'Tax',
            'subtitle' => 'VAT books, declaration datasets, tax adjustments, and audit-ready tax logs.',
            'record_table' => 'vas_tax_codes',
            'record_label' => 'Tax codes',
            'provider_config_key' => 'tax_export_adapters',
            'capabilities' => [
                ['title' => 'Tax code controls', 'description' => 'Use VAS tax codes consistently across invoice and journal postings.'],
                ['title' => 'Declaration exports', 'description' => 'Keep tax export adapters ready for declaration packages and compliance data.'],
                ['title' => 'Adjustment traceability', 'description' => 'Tax corrections keep an approval and audit trail.'],
            ],
        ],
        'einvoices' => [
            'route' => 'vasaccounting.einvoices.index',
            'path' => 'e-invoices',
            'permission' => 'vas_accounting.einvoice.manage',
            'title' => 'E-Invoices',
            'nav_label' => 'E-Invoices',
            'subtitle' => 'Provider issue, sync, cancel, replace, and correction workflows for posted invoice documents.',
            'record_table' => 'vas_einvoice_documents',
            'record_label' => 'E-invoices',
            'provider_config_key' => 'einvoice_adapters',
            'capabilities' => [
                ['title' => 'Provider-ready adapters', 'description' => 'Adapters can be swapped without changing the voucher lifecycle.'],
                ['title' => 'Document logs', 'description' => 'Every issue and sync action keeps request and response history.'],
                ['title' => 'Correction path', 'description' => 'Cancel, replace, and correction operations are prepared in the contract layer.'],
            ],
        ],
        'payroll' => [
            'route' => 'vasaccounting.payroll.index',
            'path' => 'payroll',
            'permission' => 'vas_accounting.payroll.manage',
            'title' => 'Payroll Bridge',
            'nav_label' => 'Payroll',
            'subtitle' => 'Reuse Essentials payroll as the source and convert finalized runs into VAS postings.',
            'record_table' => 'vas_payroll_batches',
            'record_label' => 'Payroll batches',
            'provider_config_key' => 'payroll_bridge_adapters',
            'capabilities' => [
                ['title' => 'Essentials reuse', 'description' => 'Payroll entry remains in Essentials while finance posting stays in VAS.'],
                ['title' => 'Accrual and payment postings', 'description' => 'Separate payroll accrual and payment sequences can flow into the ledger.'],
                ['title' => 'Branch-aware payroll', 'description' => 'Payroll batches can be tied to locations and finance dimensions.'],
            ],
        ],
        'contracts' => [
            'route' => 'vasaccounting.contracts.index',
            'path' => 'contracts',
            'permission' => 'vas_accounting.contracts.manage',
            'title' => 'Contracts',
            'nav_label' => 'Contracts',
            'subtitle' => 'Contract registry, billing milestones, advances, retention, and attachment governance.',
            'record_table' => 'vas_contracts',
            'record_label' => 'Contracts',
            'capabilities' => [
                ['title' => 'Registry and metadata', 'description' => 'Track signed contracts with project, branch, and customer/vendor linkage.'],
                ['title' => 'Advance and retention', 'description' => 'Prepare contract accounting for advances and retained amounts.'],
                ['title' => 'Attachment governance', 'description' => 'Contracts can reuse the shared document attachment and audit foundations.'],
            ],
        ],
        'loans' => [
            'route' => 'vasaccounting.loans.index',
            'path' => 'loans',
            'permission' => 'vas_accounting.loans.manage',
            'title' => 'Loans',
            'nav_label' => 'Loans',
            'subtitle' => 'Loan agreements, disbursements, repayment plans, and interest accrual readiness.',
            'record_table' => 'vas_loans',
            'record_label' => 'Loans',
            'capabilities' => [
                ['title' => 'Loan register', 'description' => 'Track lender, principal, rate, maturity, and linked bank account details.'],
                ['title' => 'Debt-service preparation', 'description' => 'Prepare disbursement, repayment, and interest posting sequences.'],
                ['title' => 'Contract linkage', 'description' => 'Tie financing to contract or investment records when needed.'],
            ],
        ],
        'costing' => [
            'route' => 'vasaccounting.costing.index',
            'path' => 'costing',
            'permission' => 'vas_accounting.costing.manage',
            'title' => 'Cost Accounting',
            'nav_label' => 'Costing',
            'subtitle' => 'Departments, cost centers, projects, and WIP-ready finance dimensions.',
            'record_table' => 'vas_cost_centers',
            'record_label' => 'Cost centers',
            'capabilities' => [
                ['title' => 'Cost dimensions', 'description' => 'Departments, cost centers, and projects are ready on voucher lines and journals.'],
                ['title' => 'Project accumulation', 'description' => 'Capture costs against projects and cost objects for later rollups.'],
                ['title' => 'Period-close traceability', 'description' => 'Dimensions carry through into ledger and budget reporting.'],
            ],
        ],
        'budgets' => [
            'route' => 'vasaccounting.budgets.index',
            'path' => 'budgets',
            'permission' => 'vas_accounting.budgets.manage',
            'title' => 'Budgets',
            'nav_label' => 'Budgets',
            'subtitle' => 'Budget headers, line planning, commitments, actuals, and variance readiness.',
            'record_table' => 'vas_budgets',
            'record_label' => 'Budgets',
            'capabilities' => [
                ['title' => 'Budget structures', 'description' => 'Budget headers and line items can tie to account and cost dimensions.'],
                ['title' => 'Commitment tracking', 'description' => 'Reserved, committed, and actual balances can be tracked separately.'],
                ['title' => 'Variance reporting', 'description' => 'Budgets are prepared for budget-vs-actual reporting by period or project.'],
            ],
        ],
        'integrations' => [
            'route' => 'vasaccounting.integrations.index',
            'path' => 'integrations',
            'permission' => 'vas_accounting.integrations.manage',
            'title' => 'Integration Hub',
            'nav_label' => 'Integrations',
            'subtitle' => 'API guard normalization, provider adapters, import/export contracts, and external finance connectors.',
            'record_table' => 'vas_posting_failures',
            'record_label' => 'Integration events',
            'provider_config_key' => 'einvoice_adapters',
            'capabilities' => [
                ['title' => 'Provider managers', 'description' => 'Dedicated managers now resolve e-invoice, payroll, bank, and tax adapters.'],
                ['title' => 'API normalization', 'description' => 'VAS API routes now align to Passport guard usage for enterprise integrations.'],
                ['title' => 'Import/export readiness', 'description' => 'Shared contracts support opening balances, statements, tax exports, and payroll bridge flows.'],
            ],
        ],
    ],
    'mandatory_posting_map_keys' => [
        'cash',
        'bank',
        'accounts_receivable',
        'accounts_payable',
        'revenue',
        'vat_output',
        'vat_input',
        'inventory',
        'cogs',
        'expense',
        'fixed_asset',
        'accumulated_depreciation',
        'depreciation_expense',
        'stock_adjustment',
        'stock_transfer',
    ],
    'default_posting_map_codes' => [
        'cash' => '111',
        'bank' => '112',
        'accounts_receivable' => '131',
        'accounts_payable' => '331',
        'revenue' => '511',
        'vat_output' => '33311',
        'vat_input' => '1331',
        'inventory' => '156',
        'cogs' => '632',
        'expense' => '6427',
        'fixed_asset' => '211',
        'accumulated_depreciation' => '2141',
        'depreciation_expense' => '6424',
        'stock_adjustment' => '632',
        'stock_transfer' => '1368',
    ],
    'voucher_sequences' => [
        ['sequence_key' => 'general_journal', 'prefix' => 'JV', 'padding' => 5],
        ['sequence_key' => 'sales_invoice', 'prefix' => 'SV', 'padding' => 5],
        ['sequence_key' => 'purchase_invoice', 'prefix' => 'PV', 'padding' => 5],
        ['sequence_key' => 'cash_receipt', 'prefix' => 'CR', 'padding' => 5],
        ['sequence_key' => 'cash_payment', 'prefix' => 'CP', 'padding' => 5],
        ['sequence_key' => 'bank_receipt', 'prefix' => 'BR', 'padding' => 5],
        ['sequence_key' => 'bank_payment', 'prefix' => 'BP', 'padding' => 5],
        ['sequence_key' => 'fund_transfer', 'prefix' => 'FT', 'padding' => 5],
        ['sequence_key' => 'sales_credit_note', 'prefix' => 'SCN', 'padding' => 5],
        ['sequence_key' => 'purchase_debit_note', 'prefix' => 'PDN', 'padding' => 5],
        ['sequence_key' => 'depreciation', 'prefix' => 'DEP', 'padding' => 5],
        ['sequence_key' => 'tool_amortization', 'prefix' => 'TAM', 'padding' => 5],
        ['sequence_key' => 'payroll_accrual', 'prefix' => 'PAY', 'padding' => 5],
        ['sequence_key' => 'payroll_payment', 'prefix' => 'PYP', 'padding' => 5],
        ['sequence_key' => 'contract_accrual', 'prefix' => 'CTR', 'padding' => 5],
        ['sequence_key' => 'loan_disbursement', 'prefix' => 'LON', 'padding' => 5],
        ['sequence_key' => 'loan_repayment', 'prefix' => 'LRP', 'padding' => 5],
        ['sequence_key' => 'budget_adjustment', 'prefix' => 'BUD', 'padding' => 5],
        ['sequence_key' => 'tax_adjustment', 'prefix' => 'TAX', 'padding' => 5],
        ['sequence_key' => 'closing', 'prefix' => 'CLS', 'padding' => 5],
    ],
    'source_document_adapters' => [
        'sell' => SellDocumentAdapter::class,
        'purchase' => PurchaseDocumentAdapter::class,
        'expense' => ExpenseDocumentAdapter::class,
        'transaction_payment' => PaymentDocumentAdapter::class,
        'sell_return' => SellReturnDocumentAdapter::class,
        'purchase_return' => PurchaseReturnDocumentAdapter::class,
        'stock_adjustment' => StockAdjustmentDocumentAdapter::class,
        'stock_transfer' => StockTransferDocumentAdapter::class,
        'opening_stock' => OpeningStockDocumentAdapter::class,
    ],
    'einvoice_adapters' => [
        'sandbox' => SandboxEInvoiceAdapter::class,
    ],
    'bank_statement_import_adapters' => [
        'manual' => NullBankStatementImportAdapter::class,
    ],
    'tax_export_adapters' => [
        'local' => LocalTaxExportAdapter::class,
    ],
    'payroll_bridge_adapters' => [
        'essentials' => EssentialsPayrollBridgeAdapter::class,
    ],
    'tax_codes' => [
        ['code' => 'VAT10_OUT', 'name' => 'VAT Output 10%', 'direction' => 'output', 'rate' => 10.0],
        ['code' => 'VAT10_IN', 'name' => 'VAT Input 10%', 'direction' => 'input', 'rate' => 10.0],
        ['code' => 'VAT8_OUT', 'name' => 'VAT Output 8%', 'direction' => 'output', 'rate' => 8.0],
        ['code' => 'VAT8_IN', 'name' => 'VAT Input 8%', 'direction' => 'input', 'rate' => 8.0],
        ['code' => 'VAT0_OUT', 'name' => 'VAT Output 0%', 'direction' => 'output', 'rate' => 0.0],
        ['code' => 'VAT_EXEMPT', 'name' => 'VAT Exempt', 'direction' => 'both', 'rate' => 0.0],
    ],
    'vn_chart' => require __DIR__ . '/vn_chart.php',
];
