<?php

return [
    'name' => 'ProjectX',
    'module_version' => '1.0',
    'quote_defaults' => [
        'expiry_days' => 14,
        'prefix' => 'RFQ',
        'remark' => "1. Delivery time: after order confirmed 30 days\n2. The quotation is firm until {{valid_until}}\n3. Shipment of port: {{shipment_port}}\n4. MOQ: One 20GP container\n5. Payment term: 30% advance payed by T/T, the 70% balance T/T against copy of B/L",
    ],
    'shipment_ports' => [
        'GUANGZHOU, CHINA',
        'SHENZHEN, CHINA',
        'SHANGHAI, CHINA',
        'NINGBO, CHINA',
        'QINGDAO, CHINA',
        'HANOI, VIETNAM',
        'HO CHI MINH, VIETNAM',
        'HAI PHONG, VIETNAM',
    ],
    'quote_mailer' => [
        'driver' => env('PROJECTX_QUOTE_MAILER_DRIVER', 'stub'),
    ],
    'quote_costing_options' => [
        'currency' => ['USD', 'EUR', 'GBP', 'SAR', 'AED'],
        'incoterm' => ['FOB', 'CIF', 'EXW', 'DDP', 'DAP'],
        'purchase_uom' => ['yd', 'm', 'kg', 'lb'],
    ],
    'fabric_construction' => [
        'types' => [
            'Knit',
            'Woven',
            'Non-woven',
            'Yarn',
            'Jacquard',
            'Warp knit',
            'Weft knit',
        ],
        'map' => [
            'Woven' => 'construction-detail-woven',
            'Jacquard' => 'construction-detail-woven',
            'Knit' => 'construction-detail-knit',
            'Warp knit' => 'construction-detail-knit',
            'Weft knit' => 'construction-detail-knit',
            'Non-woven' => 'construction-detail-non-woven',
            'Yarn' => 'construction-detail-yarn',
        ],
        'lists' => [
            'construction-detail-woven' => [
                'Bedford',
                'Broken Twill',
                'Canvas',
                'Chambray',
                'Chiffon',
                'Corduroy',
                'Crepe',
                'Denim',
                'Dobby',
                'Drill',
                'Duck',
                'Flannel',
                'Gabardine',
                'Glenplaid',
                'Herringbone',
                'Herringbone Twill',
                'Houndstooth',
                'Moleskin',
                'Oxford',
                'Pinstripe',
                'Plain weave',
                'Poplin',
                'Ripstop',
                'Sateen',
                'Satin',
                'Seersucker',
                'Taffeta',
                'Twill',
                'Twill 2/1',
                'Twill 3/1',
                'Velvet',
                'Velveteen',
            ],
            'construction-detail-knit' => [
                'Auto Stripe',
                'Cable Knit',
                'Chemical (knit lace)',
                'Double Face',
                'Double Jersey',
                'Double Knits',
                'Drop Needle',
                'Feeder Stripe',
                'Fleece',
                'French Rib',
                'French Terry',
                'Interlock',
                'Italian Fleece',
                'Jacquard',
                'Jersey',
                'Lace',
                'Mesh',
                'Milano Rib',
                'Oxford Jersey',
                'Pique',
                'Pointelle',
                'Polar Fleece',
                'Ponti-di-Roma',
                'Punto Milano',
                'Rib Knit',
                'Single Jersey',
                'Single Knits',
                'Terry',
                'Tricot',
                'Tulle',
                'Velour',
                'Waffle',
            ],
            'construction-detail-non-woven' => [
                'Bonded',
                'Felt',
                'Needle Punched',
                'Non-woven',
                'Spunbond',
                'Meltblown',
            ],
            'construction-detail-yarn' => [
                'Bi-Color',
                'Boucle',
                'Carded',
                'Chenille',
                'Combed',
                'Compact',
                'Filament',
                'Filament Yarns',
                'Gassed',
                'Heather',
                'Loop',
                'Mercerized',
                'Mohair',
                'Mouline',
                'Multicolor',
                'Neps',
                'Pima',
                'Ply Yarns',
                'Slub',
                'Spun',
                'Staple Fiber Yarns',
                'Stretch',
                'Tape',
                'Twisted',
                'Woolen',
                'Worsted',
            ],
        ],
    ],
    'chat' => [
        'enabled' => env('PROJECTX_CHAT_ENABLED', true),
        'workflow_profile' => env('PROJECTX_CHAT_WORKFLOW_PROFILE', 'dezai_assumed_v1'),
        'general_first_mode' => filter_var(env('PROJECTX_CHAT_GENERAL_FIRST_MODE', true), FILTER_VALIDATE_BOOLEAN),
        'enforce_fabric_update_match' => filter_var(env('PROJECTX_CHAT_ENFORCE_FABRIC_UPDATE_MATCH', true), FILTER_VALIDATE_BOOLEAN),
        'stream_timeout_seconds' => (int) env('PROJECTX_CHAT_STREAM_TIMEOUT_SECONDS', 180),
        'request_timeout_seconds' => (int) env('PROJECTX_CHAT_REQUEST_TIMEOUT_SECONDS', 120),
        'throttle_per_minute' => (int) env('PROJECTX_CHAT_THROTTLE_PER_MINUTE', 30),
        'default_provider' => env('PROJECTX_CHAT_DEFAULT_PROVIDER', 'openai'),
        'default_model' => env('PROJECTX_CHAT_DEFAULT_MODEL', 'gpt-4o-mini'),
        'share_ttl_hours' => (int) env('PROJECTX_CHAT_SHARE_TTL_HOURS', 168),
        'retention_days' => (int) env('PROJECTX_CHAT_RETENTION_DAYS', 90),
        'idle_timeout_minutes' => (int) env('PROJECTX_CHAT_IDLE_TIMEOUT_MINUTES', 30),
        'pii_policy' => env('PROJECTX_CHAT_PII_POLICY', 'warn'),
        'moderation_enabled' => (bool) env('PROJECTX_CHAT_MODERATION_ENABLED', false),
        'moderation_terms' => array_values(array_filter(array_map('trim', explode(',', (string) env('PROJECTX_CHAT_MODERATION_TERMS', ''))))),
        'suggested_replies' => [
            'Summarize this response in 3 bullet points.',
            'Give me practical next steps.',
            'What should I ask next?',
        ],
        'structured_reasoning_enabled' => filter_var(env('PROJECTX_CHAT_STRUCTURED_REASONING_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
        'evaluation_checks_enabled' => filter_var(env('PROJECTX_CHAT_EVALUATION_CHECKS_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
        'tools_for_reasoning_enabled' => filter_var(env('PROJECTX_CHAT_TOOLS_FOR_REASONING_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
        'project_reference_enabled' => filter_var(env('PROJECTX_CHAT_PROJECT_REFERENCE_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
        'memory_enabled' => filter_var(env('PROJECTX_CHAT_MEMORY_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
        'project_reference_path' => env('PROJECTX_CHAT_PROJECT_REFERENCE_PATH', 'Modules/ProjectX/Resources/context/chat-project-reference.md'),
        'fabric_context' => [
            'read_excluded_columns' => [
                'share_password_hash',
                'share_token',
            ],
        ],
        'fabric_updates' => [
            'writable_field_types' => [
                'name' => 'string',
                'status' => 'string',
                'fiber' => 'string',
                'purchase_price' => 'decimal',
                'sale_price' => 'decimal',
                'supplier_contact_id' => 'integer',
                'due_date' => 'date',
                'progress_percent' => 'integer',
                'description' => 'string',
                'supplier_name' => 'string',
                'supplier_code' => 'string',
                'mill_article_no' => 'string',
                'country_of_origin' => 'string',
                'fabric_sku' => 'string',
                'construction_type' => 'string',
                'construction_type_other' => 'string',
                'weave_pattern' => 'string',
                'yarn_count_denier' => 'string',
                'weight_gsm' => 'decimal',
                'width_cm' => 'decimal',
                'shrinkage_percent' => 'decimal',
                'usable_width_inch' => 'decimal',
                'price_per_meter' => 'decimal',
                'currency' => 'string',
                'minimum_order_quantity' => 'decimal',
                'payment_terms' => 'string',
                'sample_lead_time_days' => 'integer',
                'bulk_lead_time_days' => 'integer',
                'shipment_mode' => 'string',
                'port_of_loading' => 'string',
                'color_fastness' => 'string',
                'abrasion_resistance' => 'string',
                'handfeel_drape' => 'string',
                'finish_treatments' => 'string',
                'certifications' => 'string',
                'notification_email' => 'boolean',
                'notification_phone' => 'boolean',
                'fds_date' => 'date',
                'swatch_submit_date' => 'date',
                'season_department' => 'string',
                'pattern_color_name_number' => 'string',
                'performance_claims' => 'string',
                'dyeing_technique' => 'string',
                'submit_type' => 'string',
                'construction_ypi' => 'string',
                'fabric_finish' => 'string',
                'care_label' => 'string',
                'elongation' => 'string',
                'growth' => 'string',
                'recovery' => 'string',
                'elongation_25_fixed' => 'string',
                'wool_type' => 'string',
                'raw_material_origin' => 'string',
                'dyeing_type' => 'string',
                'fds_season' => 'string',
                'price_500_yds' => 'decimal',
                'price_3k' => 'decimal',
                'price_10k' => 'decimal',
                'price_25k' => 'decimal',
                'price_50k_plus' => 'decimal',
                'minimum_color_quantity' => 'decimal',
                'monthly_capacity' => 'decimal',
            ],
        ],
        'providers' => [
            'openai' => [
                'label' => 'OpenAI',
                'base_url' => env('PROJECTX_CHAT_OPENAI_BASE_URL', 'https://api.openai.com/v1'),
                'models' => [
                    'gpt-4o' => 'GPT-4o',
                    'gpt-4o-mini' => 'GPT-4o Mini',
                    'gpt-4-turbo' => 'GPT-4 Turbo',
                    'gpt-3.5-turbo' => 'GPT-3.5 Turbo',
                ],
            ],
            'gemini' => [
                'label' => 'Gemini',
                'base_url' => env('PROJECTX_CHAT_GEMINI_BASE_URL', 'https://generativelanguage.googleapis.com/v1beta'),
                'models' => [
                    'gemini-3.1-pro-preview' => 'Gemini 3.1 Pro Preview',
                    'gemini-3-flash-preview' => 'Gemini 3 Flash Preview',
                    'gemini-2.5-flash' => 'Gemini 2.5 Flash',
                    'gemini-2.5-flash-lite' => 'Gemini 2.5 Flash Lite',
                    'gemini-2.0-flash' => 'Gemini 2.0 Flash',
                    'gemini-flash-latest' => 'Gemini Flash Latest',
                ],
            ],
            'openrouter' => [
                'label' => 'OpenRouter',
                'base_url' => env('PROJECTX_CHAT_OPENROUTER_BASE_URL', 'https://openrouter.ai/api/v1'),
                'models' => [
                    'openrouter/free' => 'OpenRouter Free',
                    'openrouter/auto' => 'OpenRouter Auto',
                    'anthropic/claude-3.5-sonnet' => 'Claude 3.5 Sonnet',
                    'openai/gpt-4o' => 'OpenAI GPT-4o',
                ],
            ],
            'deepseek' => [
                'label' => 'DeepSeek',
                'base_url' => env('PROJECTX_CHAT_DEEPSEEK_BASE_URL', 'https://api.deepseek.com/v1'),
                'models' => [
                    'deepseek-chat' => 'DeepSeek Chat',
                    'deepseek-coder' => 'DeepSeek Coder',
                ],
            ],
            'groq' => [
                'label' => 'Groq',
                'base_url' => env('PROJECTX_CHAT_GROQ_BASE_URL', 'https://api.groq.com/openai/v1'),
                'models' => [
                    'llama-3.1-8b-instant' => 'Llama 3.1 8B Instant',
                    'llama-3.1-70b-versatile' => 'Llama 3.1 70B Versatile',
                    'mixtral-8x7b-32768' => 'Mixtral 8x7B',
                ],
            ],
        ],
    ],
];
