<?php

return [
    'name' => 'StorageManager',
    'module_version' => '1.5.0',
    'execution_modes' => [
        'off',
        'advisory',
        'sales_order_only',
        'strict',
    ],
    'scanner_modes' => [
        'browser_ready',
        'desktop_scanner_ready',
    ],
    'inventory_statuses' => [
        'receiving',
        'staged_in',
        'available',
        'reserved',
        'picked',
        'packed',
        'staged_out',
        'in_transit',
        'quarantine',
        'damaged',
        'count_hold',
        'blocked',
    ],
    'document_types' => [
        'receipt',
        'putaway',
        'move',
        'transfer_dispatch',
        'transfer_receipt',
        'pick',
        'pack',
        'ship',
        'damage',
        'quarantine',
        'cycle_count',
        'replenishment',
    ],
    'task_statuses' => [
        'open',
        'assigned',
        'in_progress',
        'done',
        'exception',
        'cancelled',
    ],
    'sync_statuses' => [
        'not_required',
        'pending_sync',
        'synced_unposted',
        'posted',
        'sync_error',
        'reconcile_error',
    ],
    'area_types' => [
        'receiving',
        'staging_in',
        'reserve',
        'forward_pick',
        'packing',
        'dispatch',
        'quarantine',
        'damaged',
        'count_hold',
        'virtual_in_transit',
        'legacy_zone',
    ],
    'source_document_adapters' => [
        'purchase' => \Modules\StorageManager\Services\Adapters\PurchaseSourceAdapter::class,
        'purchase_order' => \Modules\StorageManager\Services\Adapters\PurchaseOrderSourceAdapter::class,
        'stock_transfer' => \Modules\StorageManager\Services\Adapters\StockTransferSourceAdapter::class,
        'stock_adjustment' => \Modules\StorageManager\Services\Adapters\StockAdjustmentSourceAdapter::class,
        'sales_order' => \Modules\StorageManager\Services\Adapters\SalesOrderSourceAdapter::class,
    ],
    'posting_adapters' => [
        'vas' => \Modules\StorageManager\Services\Adapters\VasWarehousePostingAdapter::class,
    ],
];
